//
// Carousel5AnimationView.swift
// Generated by Core Animator version 1.3.1 on 8/26/16.
//
// DO NOT MODIFY THIS FILE. IT IS AUTO-GENERATED AND WILL BE OVERWRITTEN
//

import UIKit

@IBDesignable
class Carousel5AnimationView : UIView {


	var animationCompletions = Dictionary<CAAnimation, (Bool) -> Void>()
	var viewsByName: [String : UIView]!

	// - MARK: Life Cycle

	convenience init() {
		self.init(frame: CGRect(x: 0, y: 0, width: 750, height: 130))
	}

	override init(frame: CGRect) {
		super.init(frame: frame)
		self.setupHierarchy()
	}

	required init?(coder aDecoder: NSCoder) {
		super.init(coder: aDecoder)
		self.setupHierarchy()
	}

	// - MARK: Scaling

	override func layoutSubviews() {
		super.layoutSubviews()

		if let scalingView = self.viewsByName["__scaling__"] {
			var xScale = self.bounds.size.width / scalingView.bounds.size.width
			var yScale = self.bounds.size.height / scalingView.bounds.size.height
			switch contentMode {
			case .ScaleToFill:
				break
			case .ScaleAspectFill:
				let scale = max(xScale, yScale)
				xScale = scale
				yScale = scale
			default:
				let scale = min(xScale, yScale)
				xScale = scale
				yScale = scale
			}
			scalingView.transform = CGAffineTransformMakeScale(xScale, yScale)
			scalingView.center = CGPoint(x:CGRectGetMidX(self.bounds), y:CGRectGetMidY(self.bounds))
		}
	}

	// - MARK: Setup

	func setupHierarchy() {
		var viewsByName: [String : UIView] = [:]
		let bundle = NSBundle(forClass:self.dynamicType)
		let __scaling__ = UIView()
		__scaling__.bounds = CGRect(x:0, y:0, width:750, height:130)
		__scaling__.center = CGPoint(x:375.0, y:65.0)
		self.addSubview(__scaling__)
		viewsByName["__scaling__"] = __scaling__

		let _0029Layer12 = UIImageView()
		_0029Layer12.bounds = CGRect(x:0, y:0, width:750.0, height:130.0)
		var img0029Layer1: UIImage!
		if let imagePath = bundle.pathForResource("_0029_Layer-1.png", ofType:nil) {
			img0029Layer1 = UIImage(contentsOfFile:imagePath)
		}else {
			print("** Warning: Could not create image from '_0029_Layer-1.png'. Please make sure that it is added to the project directly (not in a folder reference).")
		}
		_0029Layer12.image = img0029Layer1
		_0029Layer12.contentMode = .Center
		_0029Layer12.layer.position = CGPoint(x:375.516, y:65.873)
		__scaling__.addSubview(_0029Layer12)
		viewsByName["_0029_Layer-1 2"] = _0029Layer12

		let _0028Layer22 = UIImageView()
		_0028Layer22.bounds = CGRect(x:0, y:0, width:750.0, height:130.0)
		var img0028Layer2: UIImage!
		if let imagePath = bundle.pathForResource("_0028_Layer-2.png", ofType:nil) {
			img0028Layer2 = UIImage(contentsOfFile:imagePath)
		}else {
			print("** Warning: Could not create image from '_0028_Layer-2.png'. Please make sure that it is added to the project directly (not in a folder reference).")
		}
		_0028Layer22.image = img0028Layer2
		_0028Layer22.contentMode = .Center
		_0028Layer22.layer.position = CGPoint(x:375.516, y:65.873)
		__scaling__.addSubview(_0028Layer22)
		viewsByName["_0028_Layer-2 2"] = _0028Layer22

		let _0027Layer32 = UIImageView()
		_0027Layer32.bounds = CGRect(x:0, y:0, width:750.0, height:130.0)
		var img0027Layer3: UIImage!
		if let imagePath = bundle.pathForResource("_0027_Layer-3.png", ofType:nil) {
			img0027Layer3 = UIImage(contentsOfFile:imagePath)
		}else {
			print("** Warning: Could not create image from '_0027_Layer-3.png'. Please make sure that it is added to the project directly (not in a folder reference).")
		}
		_0027Layer32.image = img0027Layer3
		_0027Layer32.contentMode = .Center
		_0027Layer32.layer.position = CGPoint(x:375.516, y:65.873)
		__scaling__.addSubview(_0027Layer32)
		viewsByName["_0027_Layer-3 2"] = _0027Layer32

		let _0026Layer42 = UIImageView()
		_0026Layer42.bounds = CGRect(x:0, y:0, width:750.0, height:130.0)
		var img0026Layer4: UIImage!
		if let imagePath = bundle.pathForResource("_0026_Layer-4.png", ofType:nil) {
			img0026Layer4 = UIImage(contentsOfFile:imagePath)
		}else {
			print("** Warning: Could not create image from '_0026_Layer-4.png'. Please make sure that it is added to the project directly (not in a folder reference).")
		}
		_0026Layer42.image = img0026Layer4
		_0026Layer42.contentMode = .Center
		_0026Layer42.layer.position = CGPoint(x:375.516, y:65.873)
		__scaling__.addSubview(_0026Layer42)
		viewsByName["_0026_Layer-4 2"] = _0026Layer42

		let _0025Layer52 = UIImageView()
		_0025Layer52.bounds = CGRect(x:0, y:0, width:750.0, height:130.0)
		var img0025Layer5: UIImage!
		if let imagePath = bundle.pathForResource("_0025_Layer-5.png", ofType:nil) {
			img0025Layer5 = UIImage(contentsOfFile:imagePath)
		}else {
			print("** Warning: Could not create image from '_0025_Layer-5.png'. Please make sure that it is added to the project directly (not in a folder reference).")
		}
		_0025Layer52.image = img0025Layer5
		_0025Layer52.contentMode = .Center
		_0025Layer52.layer.position = CGPoint(x:375.516, y:65.873)
		__scaling__.addSubview(_0025Layer52)
		viewsByName["_0025_Layer-5 2"] = _0025Layer52

		let _0024Layer62 = UIImageView()
		_0024Layer62.bounds = CGRect(x:0, y:0, width:750.0, height:130.0)
		var img0024Layer6: UIImage!
		if let imagePath = bundle.pathForResource("_0024_Layer-6.png", ofType:nil) {
			img0024Layer6 = UIImage(contentsOfFile:imagePath)
		}else {
			print("** Warning: Could not create image from '_0024_Layer-6.png'. Please make sure that it is added to the project directly (not in a folder reference).")
		}
		_0024Layer62.image = img0024Layer6
		_0024Layer62.contentMode = .Center
		_0024Layer62.layer.position = CGPoint(x:375.516, y:65.873)
		__scaling__.addSubview(_0024Layer62)
		viewsByName["_0024_Layer-6 2"] = _0024Layer62

		let _0023Layer72 = UIImageView()
		_0023Layer72.bounds = CGRect(x:0, y:0, width:750.0, height:130.0)
		var img0023Layer7: UIImage!
		if let imagePath = bundle.pathForResource("_0023_Layer-7.png", ofType:nil) {
			img0023Layer7 = UIImage(contentsOfFile:imagePath)
		}else {
			print("** Warning: Could not create image from '_0023_Layer-7.png'. Please make sure that it is added to the project directly (not in a folder reference).")
		}
		_0023Layer72.image = img0023Layer7
		_0023Layer72.contentMode = .Center
		_0023Layer72.layer.position = CGPoint(x:375.516, y:65.873)
		__scaling__.addSubview(_0023Layer72)
		viewsByName["_0023_Layer-7 2"] = _0023Layer72

		let _0022Layer82 = UIImageView()
		_0022Layer82.bounds = CGRect(x:0, y:0, width:750.0, height:130.0)
		var img0022Layer8: UIImage!
		if let imagePath = bundle.pathForResource("_0022_Layer-8.png", ofType:nil) {
			img0022Layer8 = UIImage(contentsOfFile:imagePath)
		}else {
			print("** Warning: Could not create image from '_0022_Layer-8.png'. Please make sure that it is added to the project directly (not in a folder reference).")
		}
		_0022Layer82.image = img0022Layer8
		_0022Layer82.contentMode = .Center
		_0022Layer82.layer.position = CGPoint(x:375.516, y:65.873)
		__scaling__.addSubview(_0022Layer82)
		viewsByName["_0022_Layer-8 2"] = _0022Layer82

		let _0021Layer92 = UIImageView()
		_0021Layer92.bounds = CGRect(x:0, y:0, width:750.0, height:130.0)
		var img0021Layer9: UIImage!
		if let imagePath = bundle.pathForResource("_0021_Layer-9.png", ofType:nil) {
			img0021Layer9 = UIImage(contentsOfFile:imagePath)
		}else {
			print("** Warning: Could not create image from '_0021_Layer-9.png'. Please make sure that it is added to the project directly (not in a folder reference).")
		}
		_0021Layer92.image = img0021Layer9
		_0021Layer92.contentMode = .Center
		_0021Layer92.layer.position = CGPoint(x:375.516, y:65.873)
		__scaling__.addSubview(_0021Layer92)
		viewsByName["_0021_Layer-9 2"] = _0021Layer92

		let _0020Layer102 = UIImageView()
		_0020Layer102.bounds = CGRect(x:0, y:0, width:750.0, height:130.0)
		var img0020Layer10: UIImage!
		if let imagePath = bundle.pathForResource("_0020_Layer-10.png", ofType:nil) {
			img0020Layer10 = UIImage(contentsOfFile:imagePath)
		}else {
			print("** Warning: Could not create image from '_0020_Layer-10.png'. Please make sure that it is added to the project directly (not in a folder reference).")
		}
		_0020Layer102.image = img0020Layer10
		_0020Layer102.contentMode = .Center
		_0020Layer102.layer.position = CGPoint(x:375.516, y:65.873)
		__scaling__.addSubview(_0020Layer102)
		viewsByName["_0020_Layer-10 2"] = _0020Layer102

		let _0019Layer112 = UIImageView()
		_0019Layer112.bounds = CGRect(x:0, y:0, width:750.0, height:130.0)
		var img0019Layer11: UIImage!
		if let imagePath = bundle.pathForResource("_0019_Layer-11.png", ofType:nil) {
			img0019Layer11 = UIImage(contentsOfFile:imagePath)
		}else {
			print("** Warning: Could not create image from '_0019_Layer-11.png'. Please make sure that it is added to the project directly (not in a folder reference).")
		}
		_0019Layer112.image = img0019Layer11
		_0019Layer112.contentMode = .Center
		_0019Layer112.layer.position = CGPoint(x:375.516, y:65.873)
		__scaling__.addSubview(_0019Layer112)
		viewsByName["_0019_Layer-11 2"] = _0019Layer112

		let _0018Layer122 = UIImageView()
		_0018Layer122.bounds = CGRect(x:0, y:0, width:750.0, height:130.0)
		var img0018Layer12: UIImage!
		if let imagePath = bundle.pathForResource("_0018_Layer-12.png", ofType:nil) {
			img0018Layer12 = UIImage(contentsOfFile:imagePath)
		}else {
			print("** Warning: Could not create image from '_0018_Layer-12.png'. Please make sure that it is added to the project directly (not in a folder reference).")
		}
		_0018Layer122.image = img0018Layer12
		_0018Layer122.contentMode = .Center
		_0018Layer122.layer.position = CGPoint(x:375.516, y:65.873)
		__scaling__.addSubview(_0018Layer122)
		viewsByName["_0018_Layer-12 2"] = _0018Layer122

		let _0017Layer132 = UIImageView()
		_0017Layer132.bounds = CGRect(x:0, y:0, width:750.0, height:130.0)
		var img0017Layer13: UIImage!
		if let imagePath = bundle.pathForResource("_0017_Layer-13.png", ofType:nil) {
			img0017Layer13 = UIImage(contentsOfFile:imagePath)
		}else {
			print("** Warning: Could not create image from '_0017_Layer-13.png'. Please make sure that it is added to the project directly (not in a folder reference).")
		}
		_0017Layer132.image = img0017Layer13
		_0017Layer132.contentMode = .Center
		_0017Layer132.layer.position = CGPoint(x:375.516, y:65.873)
		__scaling__.addSubview(_0017Layer132)
		viewsByName["_0017_Layer-13 2"] = _0017Layer132

		let _0016Layer142 = UIImageView()
		_0016Layer142.bounds = CGRect(x:0, y:0, width:750.0, height:130.0)
		var img0016Layer14: UIImage!
		if let imagePath = bundle.pathForResource("_0016_Layer-14.png", ofType:nil) {
			img0016Layer14 = UIImage(contentsOfFile:imagePath)
		}else {
			print("** Warning: Could not create image from '_0016_Layer-14.png'. Please make sure that it is added to the project directly (not in a folder reference).")
		}
		_0016Layer142.image = img0016Layer14
		_0016Layer142.contentMode = .Center
		_0016Layer142.layer.position = CGPoint(x:375.516, y:65.873)
		__scaling__.addSubview(_0016Layer142)
		viewsByName["_0016_Layer-14 2"] = _0016Layer142

		let _0015Layer152 = UIImageView()
		_0015Layer152.bounds = CGRect(x:0, y:0, width:750.0, height:130.0)
		var img0015Layer15: UIImage!
		if let imagePath = bundle.pathForResource("_0015_Layer-15.png", ofType:nil) {
			img0015Layer15 = UIImage(contentsOfFile:imagePath)
		}else {
			print("** Warning: Could not create image from '_0015_Layer-15.png'. Please make sure that it is added to the project directly (not in a folder reference).")
		}
		_0015Layer152.image = img0015Layer15
		_0015Layer152.contentMode = .Center
		_0015Layer152.layer.position = CGPoint(x:375.516, y:65.873)
		__scaling__.addSubview(_0015Layer152)
		viewsByName["_0015_Layer-15 2"] = _0015Layer152

		let _0014Layer162 = UIImageView()
		_0014Layer162.bounds = CGRect(x:0, y:0, width:750.0, height:130.0)
		var img0014Layer16: UIImage!
		if let imagePath = bundle.pathForResource("_0014_Layer-16.png", ofType:nil) {
			img0014Layer16 = UIImage(contentsOfFile:imagePath)
		}else {
			print("** Warning: Could not create image from '_0014_Layer-16.png'. Please make sure that it is added to the project directly (not in a folder reference).")
		}
		_0014Layer162.image = img0014Layer16
		_0014Layer162.contentMode = .Center
		_0014Layer162.layer.position = CGPoint(x:375.516, y:65.873)
		__scaling__.addSubview(_0014Layer162)
		viewsByName["_0014_Layer-16 2"] = _0014Layer162

		let _0013Layer172 = UIImageView()
		_0013Layer172.bounds = CGRect(x:0, y:0, width:750.0, height:130.0)
		var img0013Layer17: UIImage!
		if let imagePath = bundle.pathForResource("_0013_Layer-17.png", ofType:nil) {
			img0013Layer17 = UIImage(contentsOfFile:imagePath)
		}else {
			print("** Warning: Could not create image from '_0013_Layer-17.png'. Please make sure that it is added to the project directly (not in a folder reference).")
		}
		_0013Layer172.image = img0013Layer17
		_0013Layer172.contentMode = .Center
		_0013Layer172.layer.position = CGPoint(x:375.516, y:65.873)
		__scaling__.addSubview(_0013Layer172)
		viewsByName["_0013_Layer-17 2"] = _0013Layer172

		let _0012Layer182 = UIImageView()
		_0012Layer182.bounds = CGRect(x:0, y:0, width:750.0, height:130.0)
		var img0012Layer18: UIImage!
		if let imagePath = bundle.pathForResource("_0012_Layer-18.png", ofType:nil) {
			img0012Layer18 = UIImage(contentsOfFile:imagePath)
		}else {
			print("** Warning: Could not create image from '_0012_Layer-18.png'. Please make sure that it is added to the project directly (not in a folder reference).")
		}
		_0012Layer182.image = img0012Layer18
		_0012Layer182.contentMode = .Center
		_0012Layer182.layer.position = CGPoint(x:375.516, y:65.873)
		__scaling__.addSubview(_0012Layer182)
		viewsByName["_0012_Layer-18 2"] = _0012Layer182

		let _0011Layer192 = UIImageView()
		_0011Layer192.bounds = CGRect(x:0, y:0, width:750.0, height:130.0)
		var img0011Layer19: UIImage!
		if let imagePath = bundle.pathForResource("_0011_Layer-19.png", ofType:nil) {
			img0011Layer19 = UIImage(contentsOfFile:imagePath)
		}else {
			print("** Warning: Could not create image from '_0011_Layer-19.png'. Please make sure that it is added to the project directly (not in a folder reference).")
		}
		_0011Layer192.image = img0011Layer19
		_0011Layer192.contentMode = .Center
		_0011Layer192.layer.position = CGPoint(x:375.516, y:65.873)
		__scaling__.addSubview(_0011Layer192)
		viewsByName["_0011_Layer-19 2"] = _0011Layer192

		let _0010Layer202 = UIImageView()
		_0010Layer202.bounds = CGRect(x:0, y:0, width:750.0, height:130.0)
		var img0010Layer20: UIImage!
		if let imagePath = bundle.pathForResource("_0010_Layer-20.png", ofType:nil) {
			img0010Layer20 = UIImage(contentsOfFile:imagePath)
		}else {
			print("** Warning: Could not create image from '_0010_Layer-20.png'. Please make sure that it is added to the project directly (not in a folder reference).")
		}
		_0010Layer202.image = img0010Layer20
		_0010Layer202.contentMode = .Center
		_0010Layer202.layer.position = CGPoint(x:375.516, y:65.873)
		__scaling__.addSubview(_0010Layer202)
		viewsByName["_0010_Layer-20 2"] = _0010Layer202

		let _0009Layer212 = UIImageView()
		_0009Layer212.bounds = CGRect(x:0, y:0, width:750.0, height:130.0)
		var img0009Layer21: UIImage!
		if let imagePath = bundle.pathForResource("_0009_Layer-21.png", ofType:nil) {
			img0009Layer21 = UIImage(contentsOfFile:imagePath)
		}else {
			print("** Warning: Could not create image from '_0009_Layer-21.png'. Please make sure that it is added to the project directly (not in a folder reference).")
		}
		_0009Layer212.image = img0009Layer21
		_0009Layer212.contentMode = .Center
		_0009Layer212.layer.position = CGPoint(x:375.516, y:65.873)
		__scaling__.addSubview(_0009Layer212)
		viewsByName["_0009_Layer-21 2"] = _0009Layer212

		let _0008Layer222 = UIImageView()
		_0008Layer222.bounds = CGRect(x:0, y:0, width:750.0, height:130.0)
		var img0008Layer22: UIImage!
		if let imagePath = bundle.pathForResource("_0008_Layer-22.png", ofType:nil) {
			img0008Layer22 = UIImage(contentsOfFile:imagePath)
		}else {
			print("** Warning: Could not create image from '_0008_Layer-22.png'. Please make sure that it is added to the project directly (not in a folder reference).")
		}
		_0008Layer222.image = img0008Layer22
		_0008Layer222.contentMode = .Center
		_0008Layer222.layer.position = CGPoint(x:375.516, y:65.873)
		__scaling__.addSubview(_0008Layer222)
		viewsByName["_0008_Layer-22 2"] = _0008Layer222

		let _0007Layer232 = UIImageView()
		_0007Layer232.bounds = CGRect(x:0, y:0, width:750.0, height:130.0)
		var img0007Layer23: UIImage!
		if let imagePath = bundle.pathForResource("_0007_Layer-23.png", ofType:nil) {
			img0007Layer23 = UIImage(contentsOfFile:imagePath)
		}else {
			print("** Warning: Could not create image from '_0007_Layer-23.png'. Please make sure that it is added to the project directly (not in a folder reference).")
		}
		_0007Layer232.image = img0007Layer23
		_0007Layer232.contentMode = .Center
		_0007Layer232.layer.position = CGPoint(x:375.516, y:65.873)
		__scaling__.addSubview(_0007Layer232)
		viewsByName["_0007_Layer-23 2"] = _0007Layer232

		let _0006Layer242 = UIImageView()
		_0006Layer242.bounds = CGRect(x:0, y:0, width:750.0, height:130.0)
		var img0006Layer24: UIImage!
		if let imagePath = bundle.pathForResource("_0006_Layer-24.png", ofType:nil) {
			img0006Layer24 = UIImage(contentsOfFile:imagePath)
		}else {
			print("** Warning: Could not create image from '_0006_Layer-24.png'. Please make sure that it is added to the project directly (not in a folder reference).")
		}
		_0006Layer242.image = img0006Layer24
		_0006Layer242.contentMode = .Center
		_0006Layer242.layer.position = CGPoint(x:375.516, y:65.873)
		__scaling__.addSubview(_0006Layer242)
		viewsByName["_0006_Layer-24 2"] = _0006Layer242

		let _0005Layer252 = UIImageView()
		_0005Layer252.bounds = CGRect(x:0, y:0, width:750.0, height:130.0)
		var img0005Layer25: UIImage!
		if let imagePath = bundle.pathForResource("_0005_Layer-25.png", ofType:nil) {
			img0005Layer25 = UIImage(contentsOfFile:imagePath)
		}else {
			print("** Warning: Could not create image from '_0005_Layer-25.png'. Please make sure that it is added to the project directly (not in a folder reference).")
		}
		_0005Layer252.image = img0005Layer25
		_0005Layer252.contentMode = .Center
		_0005Layer252.layer.position = CGPoint(x:375.516, y:65.873)
		__scaling__.addSubview(_0005Layer252)
		viewsByName["_0005_Layer-25 2"] = _0005Layer252

		let _0004Layer262 = UIImageView()
		_0004Layer262.bounds = CGRect(x:0, y:0, width:750.0, height:130.0)
		var img0004Layer26: UIImage!
		if let imagePath = bundle.pathForResource("_0004_Layer-26.png", ofType:nil) {
			img0004Layer26 = UIImage(contentsOfFile:imagePath)
		}else {
			print("** Warning: Could not create image from '_0004_Layer-26.png'. Please make sure that it is added to the project directly (not in a folder reference).")
		}
		_0004Layer262.image = img0004Layer26
		_0004Layer262.contentMode = .Center
		_0004Layer262.layer.position = CGPoint(x:375.516, y:65.873)
		__scaling__.addSubview(_0004Layer262)
		viewsByName["_0004_Layer-26 2"] = _0004Layer262

		let _0003Layer272 = UIImageView()
		_0003Layer272.bounds = CGRect(x:0, y:0, width:750.0, height:130.0)
		var img0003Layer27: UIImage!
		if let imagePath = bundle.pathForResource("_0003_Layer-27.png", ofType:nil) {
			img0003Layer27 = UIImage(contentsOfFile:imagePath)
		}else {
			print("** Warning: Could not create image from '_0003_Layer-27.png'. Please make sure that it is added to the project directly (not in a folder reference).")
		}
		_0003Layer272.image = img0003Layer27
		_0003Layer272.contentMode = .Center
		_0003Layer272.layer.position = CGPoint(x:375.516, y:65.873)
		__scaling__.addSubview(_0003Layer272)
		viewsByName["_0003_Layer-27 2"] = _0003Layer272

		let _0002Layer282 = UIImageView()
		_0002Layer282.bounds = CGRect(x:0, y:0, width:750.0, height:130.0)
		var img0002Layer28: UIImage!
		if let imagePath = bundle.pathForResource("_0002_Layer-28.png", ofType:nil) {
			img0002Layer28 = UIImage(contentsOfFile:imagePath)
		}else {
			print("** Warning: Could not create image from '_0002_Layer-28.png'. Please make sure that it is added to the project directly (not in a folder reference).")
		}
		_0002Layer282.image = img0002Layer28
		_0002Layer282.contentMode = .Center
		_0002Layer282.layer.position = CGPoint(x:375.516, y:65.873)
		__scaling__.addSubview(_0002Layer282)
		viewsByName["_0002_Layer-28 2"] = _0002Layer282

		let _0001Layer292 = UIImageView()
		_0001Layer292.bounds = CGRect(x:0, y:0, width:750.0, height:130.0)
		var img0001Layer29: UIImage!
		if let imagePath = bundle.pathForResource("_0001_Layer-29.png", ofType:nil) {
			img0001Layer29 = UIImage(contentsOfFile:imagePath)
		}else {
			print("** Warning: Could not create image from '_0001_Layer-29.png'. Please make sure that it is added to the project directly (not in a folder reference).")
		}
		_0001Layer292.image = img0001Layer29
		_0001Layer292.contentMode = .Center
		_0001Layer292.layer.position = CGPoint(x:375.516, y:65.873)
		__scaling__.addSubview(_0001Layer292)
		viewsByName["_0001_Layer-29 2"] = _0001Layer292

		let _0000Layer302 = UIImageView()
		_0000Layer302.bounds = CGRect(x:0, y:0, width:750.0, height:130.0)
		var img0000Layer30: UIImage!
		if let imagePath = bundle.pathForResource("_0000_Layer-30.png", ofType:nil) {
			img0000Layer30 = UIImage(contentsOfFile:imagePath)
		}else {
			print("** Warning: Could not create image from '_0000_Layer-30.png'. Please make sure that it is added to the project directly (not in a folder reference).")
		}
		_0000Layer302.image = img0000Layer30
		_0000Layer302.contentMode = .Center
		_0000Layer302.layer.position = CGPoint(x:375.516, y:65.873)
		__scaling__.addSubview(_0000Layer302)
		viewsByName["_0000_Layer-30 2"] = _0000Layer302

		let hinge = UIImageView()
		hinge.bounds = CGRect(x:0, y:0, width:228.0, height:88.0)
		var imgHinge: UIImage!
		if let imagePath = bundle.pathForResource("Hinge.png", ofType:nil) {
			imgHinge = UIImage(contentsOfFile:imagePath)
		}else {
			print("** Warning: Could not create image from 'Hinge.png'. Please make sure that it is added to the project directly (not in a folder reference).")
		}
		hinge.image = imgHinge
		hinge.contentMode = .Center
		hinge.layer.position = CGPoint(x:381.285, y:48.389)
		__scaling__.addSubview(hinge)
		viewsByName["Hinge"] = hinge

		self.viewsByName = viewsByName
	}

	// - MARK: Carousel_5_animation

	func addCarousel5Animation() {
		addCarousel5AnimationWithBeginTime(0, fillMode: kCAFillModeBoth, removedOnCompletion: false, completion: nil)
	}

	func addCarousel5Animation(completion: ((Bool) -> Void)?) {
		addCarousel5AnimationWithBeginTime(0, fillMode: kCAFillModeBoth, removedOnCompletion: false, completion: completion)
	}

	func addCarousel5Animation(removedOnCompletion removedOnCompletion: Bool) {
		addCarousel5AnimationWithBeginTime(0, fillMode: removedOnCompletion ? kCAFillModeRemoved : kCAFillModeBoth, removedOnCompletion: removedOnCompletion, completion: nil)
	}

	func addCarousel5Animation(removedOnCompletion removedOnCompletion: Bool, completion: ((Bool) -> Void)?) {
		addCarousel5AnimationWithBeginTime(0, fillMode: removedOnCompletion ? kCAFillModeRemoved : kCAFillModeBoth, removedOnCompletion: removedOnCompletion, completion: completion)
	}

	func addCarousel5AnimationWithBeginTime(beginTime: CFTimeInterval, fillMode: String, removedOnCompletion: Bool, completion: ((Bool) -> Void)?) {
		let linearTiming = CAMediaTimingFunction(name: kCAMediaTimingFunctionLinear)
		if let complete = completion {
			let representativeAnimation = CABasicAnimation(keyPath: "not.a.real.key")
			representativeAnimation.duration = 1.210
			representativeAnimation.delegate = self
			self.layer.addAnimation(representativeAnimation, forKey: "Carousel5Animation")
			self.animationCompletions[layer.animationForKey("Carousel5Animation")!] = complete
		}

		let _0025Layer52OpacityAnimation = CAKeyframeAnimation(keyPath: "opacity")
		_0025Layer52OpacityAnimation.duration = 1.210
		_0025Layer52OpacityAnimation.values = [0.000 as Float, 0.000 as Float, 1.000 as Float, 1.000 as Float, 0.000 as Float, 0.000 as Float]
		_0025Layer52OpacityAnimation.keyTimes = [0.000 as Float, 0.124 as Float, 0.132 as Float, 0.165 as Float, 0.174 as Float, 1.000 as Float]
		_0025Layer52OpacityAnimation.timingFunctions = [linearTiming, linearTiming, linearTiming, linearTiming, linearTiming]
		_0025Layer52OpacityAnimation.beginTime = beginTime
		_0025Layer52OpacityAnimation.fillMode = fillMode
		_0025Layer52OpacityAnimation.removedOnCompletion = removedOnCompletion
		self.viewsByName["_0025_Layer-5 2"]?.layer.addAnimation(_0025Layer52OpacityAnimation, forKey:"Carousel_5_animation_Opacity")

		let _0008Layer222OpacityAnimation = CAKeyframeAnimation(keyPath: "opacity")
		_0008Layer222OpacityAnimation.duration = 1.210
		_0008Layer222OpacityAnimation.values = [0.000 as Float, 0.000 as Float, 1.000 as Float, 1.000 as Float, 0.000 as Float, 0.000 as Float]
		_0008Layer222OpacityAnimation.keyTimes = [0.000 as Float, 0.686 as Float, 0.694 as Float, 0.727 as Float, 0.736 as Float, 1.000 as Float]
		_0008Layer222OpacityAnimation.timingFunctions = [linearTiming, linearTiming, linearTiming, linearTiming, linearTiming]
		_0008Layer222OpacityAnimation.beginTime = beginTime
		_0008Layer222OpacityAnimation.fillMode = fillMode
		_0008Layer222OpacityAnimation.removedOnCompletion = removedOnCompletion
		self.viewsByName["_0008_Layer-22 2"]?.layer.addAnimation(_0008Layer222OpacityAnimation, forKey:"Carousel_5_animation_Opacity")

		let _0015Layer152OpacityAnimation = CAKeyframeAnimation(keyPath: "opacity")
		_0015Layer152OpacityAnimation.duration = 1.210
		_0015Layer152OpacityAnimation.values = [0.000 as Float, 0.000 as Float, 1.000 as Float, 1.000 as Float, 0.000 as Float, 0.000 as Float]
		_0015Layer152OpacityAnimation.keyTimes = [0.000 as Float, 0.455 as Float, 0.463 as Float, 0.496 as Float, 0.504 as Float, 1.000 as Float]
		_0015Layer152OpacityAnimation.timingFunctions = [linearTiming, linearTiming, linearTiming, linearTiming, linearTiming]
		_0015Layer152OpacityAnimation.beginTime = beginTime
		_0015Layer152OpacityAnimation.fillMode = fillMode
		_0015Layer152OpacityAnimation.removedOnCompletion = removedOnCompletion
		self.viewsByName["_0015_Layer-15 2"]?.layer.addAnimation(_0015Layer152OpacityAnimation, forKey:"Carousel_5_animation_Opacity")

		let _0027Layer32OpacityAnimation = CAKeyframeAnimation(keyPath: "opacity")
		_0027Layer32OpacityAnimation.duration = 1.210
		_0027Layer32OpacityAnimation.values = [0.000 as Float, 0.000 as Float, 1.000 as Float, 1.000 as Float, 0.000 as Float, 0.000 as Float]
		_0027Layer32OpacityAnimation.keyTimes = [0.000 as Float, 0.058 as Float, 0.066 as Float, 0.099 as Float, 0.107 as Float, 1.000 as Float]
		_0027Layer32OpacityAnimation.timingFunctions = [linearTiming, linearTiming, linearTiming, linearTiming, linearTiming]
		_0027Layer32OpacityAnimation.beginTime = beginTime
		_0027Layer32OpacityAnimation.fillMode = fillMode
		_0027Layer32OpacityAnimation.removedOnCompletion = removedOnCompletion
		self.viewsByName["_0027_Layer-3 2"]?.layer.addAnimation(_0027Layer32OpacityAnimation, forKey:"Carousel_5_animation_Opacity")

		let _0021Layer92OpacityAnimation = CAKeyframeAnimation(keyPath: "opacity")
		_0021Layer92OpacityAnimation.duration = 1.210
		_0021Layer92OpacityAnimation.values = [0.000 as Float, 0.000 as Float, 1.000 as Float, 1.000 as Float, 0.000 as Float, 0.000 as Float]
		_0021Layer92OpacityAnimation.keyTimes = [0.000 as Float, 0.256 as Float, 0.264 as Float, 0.298 as Float, 0.306 as Float, 1.000 as Float]
		_0021Layer92OpacityAnimation.timingFunctions = [linearTiming, linearTiming, linearTiming, linearTiming, linearTiming]
		_0021Layer92OpacityAnimation.beginTime = beginTime
		_0021Layer92OpacityAnimation.fillMode = fillMode
		_0021Layer92OpacityAnimation.removedOnCompletion = removedOnCompletion
		self.viewsByName["_0021_Layer-9 2"]?.layer.addAnimation(_0021Layer92OpacityAnimation, forKey:"Carousel_5_animation_Opacity")

		let _0017Layer132OpacityAnimation = CAKeyframeAnimation(keyPath: "opacity")
		_0017Layer132OpacityAnimation.duration = 1.210
		_0017Layer132OpacityAnimation.values = [0.000 as Float, 0.000 as Float, 1.000 as Float, 1.000 as Float, 0.000 as Float, 0.000 as Float]
		_0017Layer132OpacityAnimation.keyTimes = [0.000 as Float, 0.388 as Float, 0.397 as Float, 0.430 as Float, 0.438 as Float, 1.000 as Float]
		_0017Layer132OpacityAnimation.timingFunctions = [linearTiming, linearTiming, linearTiming, linearTiming, linearTiming]
		_0017Layer132OpacityAnimation.beginTime = beginTime
		_0017Layer132OpacityAnimation.fillMode = fillMode
		_0017Layer132OpacityAnimation.removedOnCompletion = removedOnCompletion
		self.viewsByName["_0017_Layer-13 2"]?.layer.addAnimation(_0017Layer132OpacityAnimation, forKey:"Carousel_5_animation_Opacity")

		let _0023Layer72OpacityAnimation = CAKeyframeAnimation(keyPath: "opacity")
		_0023Layer72OpacityAnimation.duration = 1.210
		_0023Layer72OpacityAnimation.values = [0.000 as Float, 0.000 as Float, 1.000 as Float, 1.000 as Float, 0.000 as Float, 0.000 as Float]
		_0023Layer72OpacityAnimation.keyTimes = [0.000 as Float, 0.190 as Float, 0.198 as Float, 0.231 as Float, 0.240 as Float, 1.000 as Float]
		_0023Layer72OpacityAnimation.timingFunctions = [linearTiming, linearTiming, linearTiming, linearTiming, linearTiming]
		_0023Layer72OpacityAnimation.beginTime = beginTime
		_0023Layer72OpacityAnimation.fillMode = fillMode
		_0023Layer72OpacityAnimation.removedOnCompletion = removedOnCompletion
		self.viewsByName["_0023_Layer-7 2"]?.layer.addAnimation(_0023Layer72OpacityAnimation, forKey:"Carousel_5_animation_Opacity")

		let _0011Layer192OpacityAnimation = CAKeyframeAnimation(keyPath: "opacity")
		_0011Layer192OpacityAnimation.duration = 1.210
		_0011Layer192OpacityAnimation.values = [0.000 as Float, 0.000 as Float, 1.000 as Float, 1.000 as Float, 0.000 as Float, 0.000 as Float]
		_0011Layer192OpacityAnimation.keyTimes = [0.000 as Float, 0.587 as Float, 0.595 as Float, 0.628 as Float, 0.636 as Float, 1.000 as Float]
		_0011Layer192OpacityAnimation.timingFunctions = [linearTiming, linearTiming, linearTiming, linearTiming, linearTiming]
		_0011Layer192OpacityAnimation.beginTime = beginTime
		_0011Layer192OpacityAnimation.fillMode = fillMode
		_0011Layer192OpacityAnimation.removedOnCompletion = removedOnCompletion
		self.viewsByName["_0011_Layer-19 2"]?.layer.addAnimation(_0011Layer192OpacityAnimation, forKey:"Carousel_5_animation_Opacity")

		let _0028Layer22OpacityAnimation = CAKeyframeAnimation(keyPath: "opacity")
		_0028Layer22OpacityAnimation.duration = 1.210
		_0028Layer22OpacityAnimation.values = [0.000 as Float, 0.000 as Float, 1.000 as Float, 1.000 as Float, 0.000 as Float, 0.000 as Float]
		_0028Layer22OpacityAnimation.keyTimes = [0.000 as Float, 0.025 as Float, 0.033 as Float, 0.066 as Float, 0.074 as Float, 1.000 as Float]
		_0028Layer22OpacityAnimation.timingFunctions = [linearTiming, linearTiming, linearTiming, linearTiming, linearTiming]
		_0028Layer22OpacityAnimation.beginTime = beginTime
		_0028Layer22OpacityAnimation.fillMode = fillMode
		_0028Layer22OpacityAnimation.removedOnCompletion = removedOnCompletion
		self.viewsByName["_0028_Layer-2 2"]?.layer.addAnimation(_0028Layer22OpacityAnimation, forKey:"Carousel_5_animation_Opacity")

		let _0003Layer272OpacityAnimation = CAKeyframeAnimation(keyPath: "opacity")
		_0003Layer272OpacityAnimation.duration = 1.210
		_0003Layer272OpacityAnimation.values = [0.000 as Float, 0.000 as Float, 1.000 as Float, 1.000 as Float, 0.000 as Float, 0.000 as Float]
		_0003Layer272OpacityAnimation.keyTimes = [0.000 as Float, 0.851 as Float, 0.860 as Float, 0.893 as Float, 0.901 as Float, 1.000 as Float]
		_0003Layer272OpacityAnimation.timingFunctions = [linearTiming, linearTiming, linearTiming, linearTiming, linearTiming]
		_0003Layer272OpacityAnimation.beginTime = beginTime
		_0003Layer272OpacityAnimation.fillMode = fillMode
		_0003Layer272OpacityAnimation.removedOnCompletion = removedOnCompletion
		self.viewsByName["_0003_Layer-27 2"]?.layer.addAnimation(_0003Layer272OpacityAnimation, forKey:"Carousel_5_animation_Opacity")

		let _0026Layer42OpacityAnimation = CAKeyframeAnimation(keyPath: "opacity")
		_0026Layer42OpacityAnimation.duration = 1.210
		_0026Layer42OpacityAnimation.values = [0.000 as Float, 0.000 as Float, 1.000 as Float, 1.000 as Float, 0.000 as Float, 0.000 as Float]
		_0026Layer42OpacityAnimation.keyTimes = [0.000 as Float, 0.091 as Float, 0.099 as Float, 0.132 as Float, 0.140 as Float, 1.000 as Float]
		_0026Layer42OpacityAnimation.timingFunctions = [linearTiming, linearTiming, linearTiming, linearTiming, linearTiming]
		_0026Layer42OpacityAnimation.beginTime = beginTime
		_0026Layer42OpacityAnimation.fillMode = fillMode
		_0026Layer42OpacityAnimation.removedOnCompletion = removedOnCompletion
		self.viewsByName["_0026_Layer-4 2"]?.layer.addAnimation(_0026Layer42OpacityAnimation, forKey:"Carousel_5_animation_Opacity")

		let _0001Layer292OpacityAnimation = CAKeyframeAnimation(keyPath: "opacity")
		_0001Layer292OpacityAnimation.duration = 1.210
		_0001Layer292OpacityAnimation.values = [0.000 as Float, 0.000 as Float, 1.000 as Float, 1.000 as Float, 0.000 as Float, 0.000 as Float]
		_0001Layer292OpacityAnimation.keyTimes = [0.000 as Float, 0.917 as Float, 0.926 as Float, 0.959 as Float, 0.967 as Float, 1.000 as Float]
		_0001Layer292OpacityAnimation.timingFunctions = [linearTiming, linearTiming, linearTiming, linearTiming, linearTiming]
		_0001Layer292OpacityAnimation.beginTime = beginTime
		_0001Layer292OpacityAnimation.fillMode = fillMode
		_0001Layer292OpacityAnimation.removedOnCompletion = removedOnCompletion
		self.viewsByName["_0001_Layer-29 2"]?.layer.addAnimation(_0001Layer292OpacityAnimation, forKey:"Carousel_5_animation_Opacity")

		let _0013Layer172OpacityAnimation = CAKeyframeAnimation(keyPath: "opacity")
		_0013Layer172OpacityAnimation.duration = 1.210
		_0013Layer172OpacityAnimation.values = [0.000 as Float, 0.000 as Float, 1.000 as Float, 1.000 as Float, 0.000 as Float, 0.000 as Float]
		_0013Layer172OpacityAnimation.keyTimes = [0.000 as Float, 0.521 as Float, 0.529 as Float, 0.562 as Float, 0.570 as Float, 1.000 as Float]
		_0013Layer172OpacityAnimation.timingFunctions = [linearTiming, linearTiming, linearTiming, linearTiming, linearTiming]
		_0013Layer172OpacityAnimation.beginTime = beginTime
		_0013Layer172OpacityAnimation.fillMode = fillMode
		_0013Layer172OpacityAnimation.removedOnCompletion = removedOnCompletion
		self.viewsByName["_0013_Layer-17 2"]?.layer.addAnimation(_0013Layer172OpacityAnimation, forKey:"Carousel_5_animation_Opacity")

		let _0002Layer282OpacityAnimation = CAKeyframeAnimation(keyPath: "opacity")
		_0002Layer282OpacityAnimation.duration = 1.210
		_0002Layer282OpacityAnimation.values = [0.000 as Float, 0.000 as Float, 1.000 as Float, 1.000 as Float, 0.000 as Float, 0.000 as Float]
		_0002Layer282OpacityAnimation.keyTimes = [0.000 as Float, 0.884 as Float, 0.893 as Float, 0.926 as Float, 0.934 as Float, 1.000 as Float]
		_0002Layer282OpacityAnimation.timingFunctions = [linearTiming, linearTiming, linearTiming, linearTiming, linearTiming]
		_0002Layer282OpacityAnimation.beginTime = beginTime
		_0002Layer282OpacityAnimation.fillMode = fillMode
		_0002Layer282OpacityAnimation.removedOnCompletion = removedOnCompletion
		self.viewsByName["_0002_Layer-28 2"]?.layer.addAnimation(_0002Layer282OpacityAnimation, forKey:"Carousel_5_animation_Opacity")

		let _0016Layer142OpacityAnimation = CAKeyframeAnimation(keyPath: "opacity")
		_0016Layer142OpacityAnimation.duration = 1.210
		_0016Layer142OpacityAnimation.values = [0.000 as Float, 0.000 as Float, 1.000 as Float, 1.000 as Float, 0.000 as Float, 0.000 as Float]
		_0016Layer142OpacityAnimation.keyTimes = [0.000 as Float, 0.421 as Float, 0.430 as Float, 0.463 as Float, 0.471 as Float, 1.000 as Float]
		_0016Layer142OpacityAnimation.timingFunctions = [linearTiming, linearTiming, linearTiming, linearTiming, linearTiming]
		_0016Layer142OpacityAnimation.beginTime = beginTime
		_0016Layer142OpacityAnimation.fillMode = fillMode
		_0016Layer142OpacityAnimation.removedOnCompletion = removedOnCompletion
		self.viewsByName["_0016_Layer-14 2"]?.layer.addAnimation(_0016Layer142OpacityAnimation, forKey:"Carousel_5_animation_Opacity")

		let _0010Layer202OpacityAnimation = CAKeyframeAnimation(keyPath: "opacity")
		_0010Layer202OpacityAnimation.duration = 1.210
		_0010Layer202OpacityAnimation.values = [0.000 as Float, 0.000 as Float, 1.000 as Float, 1.000 as Float, 0.000 as Float, 0.000 as Float]
		_0010Layer202OpacityAnimation.keyTimes = [0.000 as Float, 0.620 as Float, 0.628 as Float, 0.661 as Float, 0.669 as Float, 1.000 as Float]
		_0010Layer202OpacityAnimation.timingFunctions = [linearTiming, linearTiming, linearTiming, linearTiming, linearTiming]
		_0010Layer202OpacityAnimation.beginTime = beginTime
		_0010Layer202OpacityAnimation.fillMode = fillMode
		_0010Layer202OpacityAnimation.removedOnCompletion = removedOnCompletion
		self.viewsByName["_0010_Layer-20 2"]?.layer.addAnimation(_0010Layer202OpacityAnimation, forKey:"Carousel_5_animation_Opacity")

		let _0006Layer242OpacityAnimation = CAKeyframeAnimation(keyPath: "opacity")
		_0006Layer242OpacityAnimation.duration = 1.210
		_0006Layer242OpacityAnimation.values = [0.000 as Float, 0.000 as Float, 1.000 as Float, 1.000 as Float, 0.000 as Float, 0.000 as Float]
		_0006Layer242OpacityAnimation.keyTimes = [0.000 as Float, 0.752 as Float, 0.760 as Float, 0.793 as Float, 0.802 as Float, 1.000 as Float]
		_0006Layer242OpacityAnimation.timingFunctions = [linearTiming, linearTiming, linearTiming, linearTiming, linearTiming]
		_0006Layer242OpacityAnimation.beginTime = beginTime
		_0006Layer242OpacityAnimation.fillMode = fillMode
		_0006Layer242OpacityAnimation.removedOnCompletion = removedOnCompletion
		self.viewsByName["_0006_Layer-24 2"]?.layer.addAnimation(_0006Layer242OpacityAnimation, forKey:"Carousel_5_animation_Opacity")

		let _0004Layer262OpacityAnimation = CAKeyframeAnimation(keyPath: "opacity")
		_0004Layer262OpacityAnimation.duration = 1.210
		_0004Layer262OpacityAnimation.values = [0.000 as Float, 0.000 as Float, 1.000 as Float, 1.000 as Float, 0.000 as Float, 0.000 as Float]
		_0004Layer262OpacityAnimation.keyTimes = [0.000 as Float, 0.818 as Float, 0.826 as Float, 0.860 as Float, 0.868 as Float, 1.000 as Float]
		_0004Layer262OpacityAnimation.timingFunctions = [linearTiming, linearTiming, linearTiming, linearTiming, linearTiming]
		_0004Layer262OpacityAnimation.beginTime = beginTime
		_0004Layer262OpacityAnimation.fillMode = fillMode
		_0004Layer262OpacityAnimation.removedOnCompletion = removedOnCompletion
		self.viewsByName["_0004_Layer-26 2"]?.layer.addAnimation(_0004Layer262OpacityAnimation, forKey:"Carousel_5_animation_Opacity")

		let _0024Layer62OpacityAnimation = CAKeyframeAnimation(keyPath: "opacity")
		_0024Layer62OpacityAnimation.duration = 1.210
		_0024Layer62OpacityAnimation.values = [0.000 as Float, 0.000 as Float, 1.000 as Float, 1.000 as Float, 0.000 as Float, 0.000 as Float]
		_0024Layer62OpacityAnimation.keyTimes = [0.000 as Float, 0.157 as Float, 0.165 as Float, 0.198 as Float, 0.207 as Float, 1.000 as Float]
		_0024Layer62OpacityAnimation.timingFunctions = [linearTiming, linearTiming, linearTiming, linearTiming, linearTiming]
		_0024Layer62OpacityAnimation.beginTime = beginTime
		_0024Layer62OpacityAnimation.fillMode = fillMode
		_0024Layer62OpacityAnimation.removedOnCompletion = removedOnCompletion
		self.viewsByName["_0024_Layer-6 2"]?.layer.addAnimation(_0024Layer62OpacityAnimation, forKey:"Carousel_5_animation_Opacity")

		let _0005Layer252OpacityAnimation = CAKeyframeAnimation(keyPath: "opacity")
		_0005Layer252OpacityAnimation.duration = 1.210
		_0005Layer252OpacityAnimation.values = [0.000 as Float, 0.000 as Float, 1.000 as Float, 1.000 as Float, 0.000 as Float, 0.000 as Float]
		_0005Layer252OpacityAnimation.keyTimes = [0.000 as Float, 0.785 as Float, 0.793 as Float, 0.826 as Float, 0.835 as Float, 1.000 as Float]
		_0005Layer252OpacityAnimation.timingFunctions = [linearTiming, linearTiming, linearTiming, linearTiming, linearTiming]
		_0005Layer252OpacityAnimation.beginTime = beginTime
		_0005Layer252OpacityAnimation.fillMode = fillMode
		_0005Layer252OpacityAnimation.removedOnCompletion = removedOnCompletion
		self.viewsByName["_0005_Layer-25 2"]?.layer.addAnimation(_0005Layer252OpacityAnimation, forKey:"Carousel_5_animation_Opacity")

		let _0019Layer112OpacityAnimation = CAKeyframeAnimation(keyPath: "opacity")
		_0019Layer112OpacityAnimation.duration = 1.210
		_0019Layer112OpacityAnimation.values = [0.000 as Float, 0.000 as Float, 1.000 as Float, 1.000 as Float, 0.000 as Float, 0.000 as Float]
		_0019Layer112OpacityAnimation.keyTimes = [0.000 as Float, 0.322 as Float, 0.331 as Float, 0.364 as Float, 0.372 as Float, 1.000 as Float]
		_0019Layer112OpacityAnimation.timingFunctions = [linearTiming, linearTiming, linearTiming, linearTiming, linearTiming]
		_0019Layer112OpacityAnimation.beginTime = beginTime
		_0019Layer112OpacityAnimation.fillMode = fillMode
		_0019Layer112OpacityAnimation.removedOnCompletion = removedOnCompletion
		self.viewsByName["_0019_Layer-11 2"]?.layer.addAnimation(_0019Layer112OpacityAnimation, forKey:"Carousel_5_animation_Opacity")

		let _0022Layer82OpacityAnimation = CAKeyframeAnimation(keyPath: "opacity")
		_0022Layer82OpacityAnimation.duration = 1.210
		_0022Layer82OpacityAnimation.values = [0.000 as Float, 0.000 as Float, 1.000 as Float, 1.000 as Float, 0.000 as Float, 0.000 as Float]
		_0022Layer82OpacityAnimation.keyTimes = [0.000 as Float, 0.223 as Float, 0.231 as Float, 0.264 as Float, 0.273 as Float, 1.000 as Float]
		_0022Layer82OpacityAnimation.timingFunctions = [linearTiming, linearTiming, linearTiming, linearTiming, linearTiming]
		_0022Layer82OpacityAnimation.beginTime = beginTime
		_0022Layer82OpacityAnimation.fillMode = fillMode
		_0022Layer82OpacityAnimation.removedOnCompletion = removedOnCompletion
		self.viewsByName["_0022_Layer-8 2"]?.layer.addAnimation(_0022Layer82OpacityAnimation, forKey:"Carousel_5_animation_Opacity")

		let _0000Layer302OpacityAnimation = CAKeyframeAnimation(keyPath: "opacity")
		_0000Layer302OpacityAnimation.duration = 1.210
		_0000Layer302OpacityAnimation.values = [0.000 as Float, 0.000 as Float, 1.000 as Float, 1.000 as Float, 0.000 as Float]
		_0000Layer302OpacityAnimation.keyTimes = [0.000 as Float, 0.950 as Float, 0.959 as Float, 0.992 as Float, 1.000 as Float]
		_0000Layer302OpacityAnimation.timingFunctions = [linearTiming, linearTiming, linearTiming, linearTiming]
		_0000Layer302OpacityAnimation.beginTime = beginTime
		_0000Layer302OpacityAnimation.fillMode = fillMode
		_0000Layer302OpacityAnimation.removedOnCompletion = removedOnCompletion
		self.viewsByName["_0000_Layer-30 2"]?.layer.addAnimation(_0000Layer302OpacityAnimation, forKey:"Carousel_5_animation_Opacity")

		let hingeOpacityAnimation = CAKeyframeAnimation(keyPath: "opacity")
		hingeOpacityAnimation.duration = 1.210
		hingeOpacityAnimation.values = [0.000 as Float, 0.000 as Float, 1.000 as Float, 1.000 as Float]
		hingeOpacityAnimation.keyTimes = [0.000 as Float, 0.744 as Float, 0.950 as Float, 1.000 as Float]
		hingeOpacityAnimation.timingFunctions = [linearTiming, linearTiming, linearTiming]
		hingeOpacityAnimation.beginTime = beginTime
		hingeOpacityAnimation.fillMode = fillMode
		hingeOpacityAnimation.removedOnCompletion = removedOnCompletion
		self.viewsByName["Hinge"]?.layer.addAnimation(hingeOpacityAnimation, forKey:"Carousel_5_animation_Opacity")

		let _0009Layer212OpacityAnimation = CAKeyframeAnimation(keyPath: "opacity")
		_0009Layer212OpacityAnimation.duration = 1.210
		_0009Layer212OpacityAnimation.values = [0.000 as Float, 0.000 as Float, 1.000 as Float, 1.000 as Float, 0.000 as Float, 0.000 as Float]
		_0009Layer212OpacityAnimation.keyTimes = [0.000 as Float, 0.653 as Float, 0.661 as Float, 0.694 as Float, 0.702 as Float, 1.000 as Float]
		_0009Layer212OpacityAnimation.timingFunctions = [linearTiming, linearTiming, linearTiming, linearTiming, linearTiming]
		_0009Layer212OpacityAnimation.beginTime = beginTime
		_0009Layer212OpacityAnimation.fillMode = fillMode
		_0009Layer212OpacityAnimation.removedOnCompletion = removedOnCompletion
		self.viewsByName["_0009_Layer-21 2"]?.layer.addAnimation(_0009Layer212OpacityAnimation, forKey:"Carousel_5_animation_Opacity")

		let _0018Layer122OpacityAnimation = CAKeyframeAnimation(keyPath: "opacity")
		_0018Layer122OpacityAnimation.duration = 1.210
		_0018Layer122OpacityAnimation.values = [0.000 as Float, 0.000 as Float, 1.000 as Float, 1.000 as Float, 0.000 as Float, 0.000 as Float]
		_0018Layer122OpacityAnimation.keyTimes = [0.000 as Float, 0.355 as Float, 0.364 as Float, 0.397 as Float, 0.405 as Float, 1.000 as Float]
		_0018Layer122OpacityAnimation.timingFunctions = [linearTiming, linearTiming, linearTiming, linearTiming, linearTiming]
		_0018Layer122OpacityAnimation.beginTime = beginTime
		_0018Layer122OpacityAnimation.fillMode = fillMode
		_0018Layer122OpacityAnimation.removedOnCompletion = removedOnCompletion
		self.viewsByName["_0018_Layer-12 2"]?.layer.addAnimation(_0018Layer122OpacityAnimation, forKey:"Carousel_5_animation_Opacity")

		let _0007Layer232OpacityAnimation = CAKeyframeAnimation(keyPath: "opacity")
		_0007Layer232OpacityAnimation.duration = 1.210
		_0007Layer232OpacityAnimation.values = [0.000 as Float, 0.000 as Float, 1.000 as Float, 1.000 as Float, 0.000 as Float, 0.000 as Float]
		_0007Layer232OpacityAnimation.keyTimes = [0.000 as Float, 0.719 as Float, 0.727 as Float, 0.760 as Float, 0.769 as Float, 1.000 as Float]
		_0007Layer232OpacityAnimation.timingFunctions = [linearTiming, linearTiming, linearTiming, linearTiming, linearTiming]
		_0007Layer232OpacityAnimation.beginTime = beginTime
		_0007Layer232OpacityAnimation.fillMode = fillMode
		_0007Layer232OpacityAnimation.removedOnCompletion = removedOnCompletion
		self.viewsByName["_0007_Layer-23 2"]?.layer.addAnimation(_0007Layer232OpacityAnimation, forKey:"Carousel_5_animation_Opacity")

		let _0012Layer182OpacityAnimation = CAKeyframeAnimation(keyPath: "opacity")
		_0012Layer182OpacityAnimation.duration = 1.210
		_0012Layer182OpacityAnimation.values = [0.000 as Float, 0.000 as Float, 1.000 as Float, 1.000 as Float, 0.000 as Float, 0.000 as Float]
		_0012Layer182OpacityAnimation.keyTimes = [0.000 as Float, 0.554 as Float, 0.562 as Float, 0.595 as Float, 0.603 as Float, 1.000 as Float]
		_0012Layer182OpacityAnimation.timingFunctions = [linearTiming, linearTiming, linearTiming, linearTiming, linearTiming]
		_0012Layer182OpacityAnimation.beginTime = beginTime
		_0012Layer182OpacityAnimation.fillMode = fillMode
		_0012Layer182OpacityAnimation.removedOnCompletion = removedOnCompletion
		self.viewsByName["_0012_Layer-18 2"]?.layer.addAnimation(_0012Layer182OpacityAnimation, forKey:"Carousel_5_animation_Opacity")

		let _0014Layer162OpacityAnimation = CAKeyframeAnimation(keyPath: "opacity")
		_0014Layer162OpacityAnimation.duration = 1.210
		_0014Layer162OpacityAnimation.values = [0.000 as Float, 0.000 as Float, 1.000 as Float, 1.000 as Float, 0.000 as Float, 0.000 as Float]
		_0014Layer162OpacityAnimation.keyTimes = [0.000 as Float, 0.488 as Float, 0.496 as Float, 0.529 as Float, 0.537 as Float, 1.000 as Float]
		_0014Layer162OpacityAnimation.timingFunctions = [linearTiming, linearTiming, linearTiming, linearTiming, linearTiming]
		_0014Layer162OpacityAnimation.beginTime = beginTime
		_0014Layer162OpacityAnimation.fillMode = fillMode
		_0014Layer162OpacityAnimation.removedOnCompletion = removedOnCompletion
		self.viewsByName["_0014_Layer-16 2"]?.layer.addAnimation(_0014Layer162OpacityAnimation, forKey:"Carousel_5_animation_Opacity")

		let _0020Layer102OpacityAnimation = CAKeyframeAnimation(keyPath: "opacity")
		_0020Layer102OpacityAnimation.duration = 1.210
		_0020Layer102OpacityAnimation.values = [0.000 as Float, 0.000 as Float, 1.000 as Float, 1.000 as Float, 0.000 as Float, 0.000 as Float]
		_0020Layer102OpacityAnimation.keyTimes = [0.000 as Float, 0.289 as Float, 0.298 as Float, 0.331 as Float, 0.339 as Float, 1.000 as Float]
		_0020Layer102OpacityAnimation.timingFunctions = [linearTiming, linearTiming, linearTiming, linearTiming, linearTiming]
		_0020Layer102OpacityAnimation.beginTime = beginTime
		_0020Layer102OpacityAnimation.fillMode = fillMode
		_0020Layer102OpacityAnimation.removedOnCompletion = removedOnCompletion
		self.viewsByName["_0020_Layer-10 2"]?.layer.addAnimation(_0020Layer102OpacityAnimation, forKey:"Carousel_5_animation_Opacity")
	}

	func removeCarousel5Animation() {
		self.layer.removeAnimationForKey("Carousel5Animation")
		self.viewsByName["_0025_Layer-5 2"]?.layer.removeAnimationForKey("Carousel_5_animation_Opacity")
		self.viewsByName["_0008_Layer-22 2"]?.layer.removeAnimationForKey("Carousel_5_animation_Opacity")
		self.viewsByName["_0015_Layer-15 2"]?.layer.removeAnimationForKey("Carousel_5_animation_Opacity")
		self.viewsByName["_0027_Layer-3 2"]?.layer.removeAnimationForKey("Carousel_5_animation_Opacity")
		self.viewsByName["_0021_Layer-9 2"]?.layer.removeAnimationForKey("Carousel_5_animation_Opacity")
		self.viewsByName["_0017_Layer-13 2"]?.layer.removeAnimationForKey("Carousel_5_animation_Opacity")
		self.viewsByName["_0023_Layer-7 2"]?.layer.removeAnimationForKey("Carousel_5_animation_Opacity")
		self.viewsByName["_0011_Layer-19 2"]?.layer.removeAnimationForKey("Carousel_5_animation_Opacity")
		self.viewsByName["_0028_Layer-2 2"]?.layer.removeAnimationForKey("Carousel_5_animation_Opacity")
		self.viewsByName["_0003_Layer-27 2"]?.layer.removeAnimationForKey("Carousel_5_animation_Opacity")
		self.viewsByName["_0026_Layer-4 2"]?.layer.removeAnimationForKey("Carousel_5_animation_Opacity")
		self.viewsByName["_0001_Layer-29 2"]?.layer.removeAnimationForKey("Carousel_5_animation_Opacity")
		self.viewsByName["_0013_Layer-17 2"]?.layer.removeAnimationForKey("Carousel_5_animation_Opacity")
		self.viewsByName["_0002_Layer-28 2"]?.layer.removeAnimationForKey("Carousel_5_animation_Opacity")
		self.viewsByName["_0016_Layer-14 2"]?.layer.removeAnimationForKey("Carousel_5_animation_Opacity")
		self.viewsByName["_0010_Layer-20 2"]?.layer.removeAnimationForKey("Carousel_5_animation_Opacity")
		self.viewsByName["_0006_Layer-24 2"]?.layer.removeAnimationForKey("Carousel_5_animation_Opacity")
		self.viewsByName["_0004_Layer-26 2"]?.layer.removeAnimationForKey("Carousel_5_animation_Opacity")
		self.viewsByName["_0024_Layer-6 2"]?.layer.removeAnimationForKey("Carousel_5_animation_Opacity")
		self.viewsByName["_0005_Layer-25 2"]?.layer.removeAnimationForKey("Carousel_5_animation_Opacity")
		self.viewsByName["_0019_Layer-11 2"]?.layer.removeAnimationForKey("Carousel_5_animation_Opacity")
		self.viewsByName["_0022_Layer-8 2"]?.layer.removeAnimationForKey("Carousel_5_animation_Opacity")
		self.viewsByName["_0000_Layer-30 2"]?.layer.removeAnimationForKey("Carousel_5_animation_Opacity")
		self.viewsByName["Hinge"]?.layer.removeAnimationForKey("Carousel_5_animation_Opacity")
		self.viewsByName["_0009_Layer-21 2"]?.layer.removeAnimationForKey("Carousel_5_animation_Opacity")
		self.viewsByName["_0018_Layer-12 2"]?.layer.removeAnimationForKey("Carousel_5_animation_Opacity")
		self.viewsByName["_0007_Layer-23 2"]?.layer.removeAnimationForKey("Carousel_5_animation_Opacity")
		self.viewsByName["_0012_Layer-18 2"]?.layer.removeAnimationForKey("Carousel_5_animation_Opacity")
		self.viewsByName["_0014_Layer-16 2"]?.layer.removeAnimationForKey("Carousel_5_animation_Opacity")
		self.viewsByName["_0020_Layer-10 2"]?.layer.removeAnimationForKey("Carousel_5_animation_Opacity")
	}

	override func animationDidStop(anim: CAAnimation, finished flag: Bool) {
		if let completion = self.animationCompletions[anim] {
			self.animationCompletions.removeValueForKey(anim)
			completion(flag)
		}
	}

	func removeAllAnimations() {
		for subview in viewsByName.values {
			subview.layer.removeAllAnimations()
		}
		self.layer.removeAnimationForKey("Carousel5Animation")
	}
}