//
// Carousel4AnimationView.swift
// Generated by Core Animator version 1.3.1 on 8/24/16.
//
// DO NOT MODIFY THIS FILE. IT IS AUTO-GENERATED AND WILL BE OVERWRITTEN
//

import UIKit

@IBDesignable
class Carousel4AnimationView : UIView {


	var animationCompletions = Dictionary<CAAnimation, (Bool) -> Void>()
	var viewsByName: [String : UIView]!

	// - MARK: Life Cycle

	convenience init() {
		self.init(frame: CGRect(x: 0, y: 0, width: 750, height: 285))
	}

	override init(frame: CGRect) {
		super.init(frame: frame)
		self.setupHierarchy()
	}

	required init?(coder aDecoder: NSCoder) {
		super.init(coder: aDecoder)
		self.setupHierarchy()
	}

	// - MARK: Scaling

	override func layoutSubviews() {
		super.layoutSubviews()

		if let scalingView = self.viewsByName["__scaling__"] {
			var xScale = self.bounds.size.width / scalingView.bounds.size.width
			var yScale = self.bounds.size.height / scalingView.bounds.size.height
			switch contentMode {
			case .ScaleToFill:
				break
			case .ScaleAspectFill:
				let scale = max(xScale, yScale)
				xScale = scale
				yScale = scale
			default:
				let scale = min(xScale, yScale)
				xScale = scale
				yScale = scale
			}
			scalingView.transform = CGAffineTransformMakeScale(xScale, yScale)
			scalingView.center = CGPoint(x:CGRectGetMidX(self.bounds), y:CGRectGetMidY(self.bounds))
		}
	}

	// - MARK: Setup

	func setupHierarchy() {
		var viewsByName: [String : UIView] = [:]
		let bundle = NSBundle(forClass:self.dynamicType)
		let __scaling__ = UIView()
		__scaling__.bounds = CGRect(x:0, y:0, width:750, height:285)
		__scaling__.center = CGPoint(x:375.0, y:142.5)
		self.addSubview(__scaling__)
		viewsByName["__scaling__"] = __scaling__

		let _0000Layer31 = UIImageView()
		_0000Layer31.bounds = CGRect(x:0, y:0, width:750.0, height:285.0)
		var img0000Layer31: UIImage!
		if let imagePath = bundle.pathForResource("_0000_Layer-31.png", ofType:nil) {
			img0000Layer31 = UIImage(contentsOfFile:imagePath)
		}else {
			print("** Warning: Could not create image from '_0000_Layer-31.png'. Please make sure that it is added to the project directly (not in a folder reference).")
		}
		_0000Layer31.image = img0000Layer31
		_0000Layer31.contentMode = .Center
		_0000Layer31.layer.position = CGPoint(x:375.000, y:142.500)
		__scaling__.addSubview(_0000Layer31)
		viewsByName["_0000_Layer-31"] = _0000Layer31

		let _0001Layer30 = UIImageView()
		_0001Layer30.bounds = CGRect(x:0, y:0, width:750.0, height:285.0)
		var img0001Layer30: UIImage!
		if let imagePath = bundle.pathForResource("_0001_Layer-30.png", ofType:nil) {
			img0001Layer30 = UIImage(contentsOfFile:imagePath)
		}else {
			print("** Warning: Could not create image from '_0001_Layer-30.png'. Please make sure that it is added to the project directly (not in a folder reference).")
		}
		_0001Layer30.image = img0001Layer30
		_0001Layer30.contentMode = .Center
		_0001Layer30.layer.position = CGPoint(x:375.000, y:142.500)
		__scaling__.addSubview(_0001Layer30)
		viewsByName["_0001_Layer-30"] = _0001Layer30

		let _0002Layer29 = UIImageView()
		_0002Layer29.bounds = CGRect(x:0, y:0, width:750.0, height:285.0)
		var img0002Layer29: UIImage!
		if let imagePath = bundle.pathForResource("_0002_Layer-29.png", ofType:nil) {
			img0002Layer29 = UIImage(contentsOfFile:imagePath)
		}else {
			print("** Warning: Could not create image from '_0002_Layer-29.png'. Please make sure that it is added to the project directly (not in a folder reference).")
		}
		_0002Layer29.image = img0002Layer29
		_0002Layer29.contentMode = .Center
		_0002Layer29.layer.position = CGPoint(x:375.000, y:142.500)
		__scaling__.addSubview(_0002Layer29)
		viewsByName["_0002_Layer-29"] = _0002Layer29

		let _0003Layer28 = UIImageView()
		_0003Layer28.bounds = CGRect(x:0, y:0, width:750.0, height:285.0)
		var img0003Layer28: UIImage!
		if let imagePath = bundle.pathForResource("_0003_Layer-28.png", ofType:nil) {
			img0003Layer28 = UIImage(contentsOfFile:imagePath)
		}else {
			print("** Warning: Could not create image from '_0003_Layer-28.png'. Please make sure that it is added to the project directly (not in a folder reference).")
		}
		_0003Layer28.image = img0003Layer28
		_0003Layer28.contentMode = .Center
		_0003Layer28.layer.position = CGPoint(x:375.000, y:142.500)
		__scaling__.addSubview(_0003Layer28)
		viewsByName["_0003_Layer-28"] = _0003Layer28

		let _0004Layer27 = UIImageView()
		_0004Layer27.bounds = CGRect(x:0, y:0, width:750.0, height:285.0)
		var img0004Layer27: UIImage!
		if let imagePath = bundle.pathForResource("_0004_Layer-27.png", ofType:nil) {
			img0004Layer27 = UIImage(contentsOfFile:imagePath)
		}else {
			print("** Warning: Could not create image from '_0004_Layer-27.png'. Please make sure that it is added to the project directly (not in a folder reference).")
		}
		_0004Layer27.image = img0004Layer27
		_0004Layer27.contentMode = .Center
		_0004Layer27.layer.position = CGPoint(x:375.000, y:142.500)
		__scaling__.addSubview(_0004Layer27)
		viewsByName["_0004_Layer-27"] = _0004Layer27

		let _0005Layer26 = UIImageView()
		_0005Layer26.bounds = CGRect(x:0, y:0, width:750.0, height:285.0)
		var img0005Layer26: UIImage!
		if let imagePath = bundle.pathForResource("_0005_Layer-26.png", ofType:nil) {
			img0005Layer26 = UIImage(contentsOfFile:imagePath)
		}else {
			print("** Warning: Could not create image from '_0005_Layer-26.png'. Please make sure that it is added to the project directly (not in a folder reference).")
		}
		_0005Layer26.image = img0005Layer26
		_0005Layer26.contentMode = .Center
		_0005Layer26.layer.position = CGPoint(x:375.000, y:142.500)
		__scaling__.addSubview(_0005Layer26)
		viewsByName["_0005_Layer-26"] = _0005Layer26

		let _0006Layer25 = UIImageView()
		_0006Layer25.bounds = CGRect(x:0, y:0, width:750.0, height:285.0)
		var img0006Layer25: UIImage!
		if let imagePath = bundle.pathForResource("_0006_Layer-25.png", ofType:nil) {
			img0006Layer25 = UIImage(contentsOfFile:imagePath)
		}else {
			print("** Warning: Could not create image from '_0006_Layer-25.png'. Please make sure that it is added to the project directly (not in a folder reference).")
		}
		_0006Layer25.image = img0006Layer25
		_0006Layer25.contentMode = .Center
		_0006Layer25.layer.position = CGPoint(x:375.000, y:142.500)
		__scaling__.addSubview(_0006Layer25)
		viewsByName["_0006_Layer-25"] = _0006Layer25

		let _0007Layer24 = UIImageView()
		_0007Layer24.bounds = CGRect(x:0, y:0, width:750.0, height:285.0)
		var img0007Layer24: UIImage!
		if let imagePath = bundle.pathForResource("_0007_Layer-24.png", ofType:nil) {
			img0007Layer24 = UIImage(contentsOfFile:imagePath)
		}else {
			print("** Warning: Could not create image from '_0007_Layer-24.png'. Please make sure that it is added to the project directly (not in a folder reference).")
		}
		_0007Layer24.image = img0007Layer24
		_0007Layer24.contentMode = .Center
		_0007Layer24.layer.position = CGPoint(x:375.000, y:142.500)
		__scaling__.addSubview(_0007Layer24)
		viewsByName["_0007_Layer-24"] = _0007Layer24

		let _0008Layer23 = UIImageView()
		_0008Layer23.bounds = CGRect(x:0, y:0, width:750.0, height:285.0)
		var img0008Layer23: UIImage!
		if let imagePath = bundle.pathForResource("_0008_Layer-23.png", ofType:nil) {
			img0008Layer23 = UIImage(contentsOfFile:imagePath)
		}else {
			print("** Warning: Could not create image from '_0008_Layer-23.png'. Please make sure that it is added to the project directly (not in a folder reference).")
		}
		_0008Layer23.image = img0008Layer23
		_0008Layer23.contentMode = .Center
		_0008Layer23.layer.position = CGPoint(x:375.000, y:142.500)
		__scaling__.addSubview(_0008Layer23)
		viewsByName["_0008_Layer-23"] = _0008Layer23

		let _0009Layer22 = UIImageView()
		_0009Layer22.bounds = CGRect(x:0, y:0, width:750.0, height:285.0)
		var img0009Layer22: UIImage!
		if let imagePath = bundle.pathForResource("_0009_Layer-22.png", ofType:nil) {
			img0009Layer22 = UIImage(contentsOfFile:imagePath)
		}else {
			print("** Warning: Could not create image from '_0009_Layer-22.png'. Please make sure that it is added to the project directly (not in a folder reference).")
		}
		_0009Layer22.image = img0009Layer22
		_0009Layer22.contentMode = .Center
		_0009Layer22.layer.position = CGPoint(x:375.000, y:142.500)
		__scaling__.addSubview(_0009Layer22)
		viewsByName["_0009_Layer-22"] = _0009Layer22

		let _0010Layer21 = UIImageView()
		_0010Layer21.bounds = CGRect(x:0, y:0, width:750.0, height:285.0)
		var img0010Layer21: UIImage!
		if let imagePath = bundle.pathForResource("_0010_Layer-21.png", ofType:nil) {
			img0010Layer21 = UIImage(contentsOfFile:imagePath)
		}else {
			print("** Warning: Could not create image from '_0010_Layer-21.png'. Please make sure that it is added to the project directly (not in a folder reference).")
		}
		_0010Layer21.image = img0010Layer21
		_0010Layer21.contentMode = .Center
		_0010Layer21.layer.position = CGPoint(x:375.000, y:142.500)
		__scaling__.addSubview(_0010Layer21)
		viewsByName["_0010_Layer-21"] = _0010Layer21

		let _0011Layer20 = UIImageView()
		_0011Layer20.bounds = CGRect(x:0, y:0, width:750.0, height:285.0)
		var img0011Layer20: UIImage!
		if let imagePath = bundle.pathForResource("_0011_Layer-20.png", ofType:nil) {
			img0011Layer20 = UIImage(contentsOfFile:imagePath)
		}else {
			print("** Warning: Could not create image from '_0011_Layer-20.png'. Please make sure that it is added to the project directly (not in a folder reference).")
		}
		_0011Layer20.image = img0011Layer20
		_0011Layer20.contentMode = .Center
		_0011Layer20.layer.position = CGPoint(x:375.000, y:142.500)
		__scaling__.addSubview(_0011Layer20)
		viewsByName["_0011_Layer-20"] = _0011Layer20

		let _0012Layer19 = UIImageView()
		_0012Layer19.bounds = CGRect(x:0, y:0, width:750.0, height:285.0)
		var img0012Layer19: UIImage!
		if let imagePath = bundle.pathForResource("_0012_Layer-19.png", ofType:nil) {
			img0012Layer19 = UIImage(contentsOfFile:imagePath)
		}else {
			print("** Warning: Could not create image from '_0012_Layer-19.png'. Please make sure that it is added to the project directly (not in a folder reference).")
		}
		_0012Layer19.image = img0012Layer19
		_0012Layer19.contentMode = .Center
		_0012Layer19.layer.position = CGPoint(x:375.000, y:142.500)
		__scaling__.addSubview(_0012Layer19)
		viewsByName["_0012_Layer-19"] = _0012Layer19

		let _0013Layer18 = UIImageView()
		_0013Layer18.bounds = CGRect(x:0, y:0, width:750.0, height:285.0)
		var img0013Layer18: UIImage!
		if let imagePath = bundle.pathForResource("_0013_Layer-18.png", ofType:nil) {
			img0013Layer18 = UIImage(contentsOfFile:imagePath)
		}else {
			print("** Warning: Could not create image from '_0013_Layer-18.png'. Please make sure that it is added to the project directly (not in a folder reference).")
		}
		_0013Layer18.image = img0013Layer18
		_0013Layer18.contentMode = .Center
		_0013Layer18.layer.position = CGPoint(x:375.000, y:142.500)
		__scaling__.addSubview(_0013Layer18)
		viewsByName["_0013_Layer-18"] = _0013Layer18

		let _0014Layer17 = UIImageView()
		_0014Layer17.bounds = CGRect(x:0, y:0, width:750.0, height:285.0)
		var img0014Layer17: UIImage!
		if let imagePath = bundle.pathForResource("_0014_Layer-17.png", ofType:nil) {
			img0014Layer17 = UIImage(contentsOfFile:imagePath)
		}else {
			print("** Warning: Could not create image from '_0014_Layer-17.png'. Please make sure that it is added to the project directly (not in a folder reference).")
		}
		_0014Layer17.image = img0014Layer17
		_0014Layer17.contentMode = .Center
		_0014Layer17.layer.position = CGPoint(x:375.000, y:142.500)
		__scaling__.addSubview(_0014Layer17)
		viewsByName["_0014_Layer-17"] = _0014Layer17

		let _0015Layer16 = UIImageView()
		_0015Layer16.bounds = CGRect(x:0, y:0, width:750.0, height:285.0)
		var img0015Layer16: UIImage!
		if let imagePath = bundle.pathForResource("_0015_Layer-16.png", ofType:nil) {
			img0015Layer16 = UIImage(contentsOfFile:imagePath)
		}else {
			print("** Warning: Could not create image from '_0015_Layer-16.png'. Please make sure that it is added to the project directly (not in a folder reference).")
		}
		_0015Layer16.image = img0015Layer16
		_0015Layer16.contentMode = .Center
		_0015Layer16.layer.position = CGPoint(x:375.000, y:142.500)
		__scaling__.addSubview(_0015Layer16)
		viewsByName["_0015_Layer-16"] = _0015Layer16

		let _0016Layer15 = UIImageView()
		_0016Layer15.bounds = CGRect(x:0, y:0, width:750.0, height:285.0)
		var img0016Layer15: UIImage!
		if let imagePath = bundle.pathForResource("_0016_Layer-15.png", ofType:nil) {
			img0016Layer15 = UIImage(contentsOfFile:imagePath)
		}else {
			print("** Warning: Could not create image from '_0016_Layer-15.png'. Please make sure that it is added to the project directly (not in a folder reference).")
		}
		_0016Layer15.image = img0016Layer15
		_0016Layer15.contentMode = .Center
		_0016Layer15.layer.position = CGPoint(x:375.000, y:142.500)
		__scaling__.addSubview(_0016Layer15)
		viewsByName["_0016_Layer-15"] = _0016Layer15

		let _0017Layer14 = UIImageView()
		_0017Layer14.bounds = CGRect(x:0, y:0, width:750.0, height:285.0)
		var img0017Layer14: UIImage!
		if let imagePath = bundle.pathForResource("_0017_Layer-14.png", ofType:nil) {
			img0017Layer14 = UIImage(contentsOfFile:imagePath)
		}else {
			print("** Warning: Could not create image from '_0017_Layer-14.png'. Please make sure that it is added to the project directly (not in a folder reference).")
		}
		_0017Layer14.image = img0017Layer14
		_0017Layer14.contentMode = .Center
		_0017Layer14.layer.position = CGPoint(x:375.000, y:142.500)
		__scaling__.addSubview(_0017Layer14)
		viewsByName["_0017_Layer-14"] = _0017Layer14

		let _0018Layer13 = UIImageView()
		_0018Layer13.bounds = CGRect(x:0, y:0, width:750.0, height:285.0)
		var img0018Layer13: UIImage!
		if let imagePath = bundle.pathForResource("_0018_Layer-13.png", ofType:nil) {
			img0018Layer13 = UIImage(contentsOfFile:imagePath)
		}else {
			print("** Warning: Could not create image from '_0018_Layer-13.png'. Please make sure that it is added to the project directly (not in a folder reference).")
		}
		_0018Layer13.image = img0018Layer13
		_0018Layer13.contentMode = .Center
		_0018Layer13.layer.position = CGPoint(x:375.000, y:142.500)
		__scaling__.addSubview(_0018Layer13)
		viewsByName["_0018_Layer-13"] = _0018Layer13

		let _0019Layer12 = UIImageView()
		_0019Layer12.bounds = CGRect(x:0, y:0, width:750.0, height:285.0)
		var img0019Layer12: UIImage!
		if let imagePath = bundle.pathForResource("_0019_Layer-12.png", ofType:nil) {
			img0019Layer12 = UIImage(contentsOfFile:imagePath)
		}else {
			print("** Warning: Could not create image from '_0019_Layer-12.png'. Please make sure that it is added to the project directly (not in a folder reference).")
		}
		_0019Layer12.image = img0019Layer12
		_0019Layer12.contentMode = .Center
		_0019Layer12.layer.position = CGPoint(x:375.000, y:142.500)
		__scaling__.addSubview(_0019Layer12)
		viewsByName["_0019_Layer-12"] = _0019Layer12

		let _0020Layer11 = UIImageView()
		_0020Layer11.bounds = CGRect(x:0, y:0, width:750.0, height:285.0)
		var img0020Layer11: UIImage!
		if let imagePath = bundle.pathForResource("_0020_Layer-11.png", ofType:nil) {
			img0020Layer11 = UIImage(contentsOfFile:imagePath)
		}else {
			print("** Warning: Could not create image from '_0020_Layer-11.png'. Please make sure that it is added to the project directly (not in a folder reference).")
		}
		_0020Layer11.image = img0020Layer11
		_0020Layer11.contentMode = .Center
		_0020Layer11.layer.position = CGPoint(x:375.000, y:142.500)
		__scaling__.addSubview(_0020Layer11)
		viewsByName["_0020_Layer-11"] = _0020Layer11

		let _0021Layer10 = UIImageView()
		_0021Layer10.bounds = CGRect(x:0, y:0, width:750.0, height:285.0)
		var img0021Layer10: UIImage!
		if let imagePath = bundle.pathForResource("_0021_Layer-10.png", ofType:nil) {
			img0021Layer10 = UIImage(contentsOfFile:imagePath)
		}else {
			print("** Warning: Could not create image from '_0021_Layer-10.png'. Please make sure that it is added to the project directly (not in a folder reference).")
		}
		_0021Layer10.image = img0021Layer10
		_0021Layer10.contentMode = .Center
		_0021Layer10.layer.position = CGPoint(x:375.000, y:142.500)
		__scaling__.addSubview(_0021Layer10)
		viewsByName["_0021_Layer-10"] = _0021Layer10

		let _0022Layer9 = UIImageView()
		_0022Layer9.bounds = CGRect(x:0, y:0, width:750.0, height:285.0)
		var img0022Layer9: UIImage!
		if let imagePath = bundle.pathForResource("_0022_Layer-9.png", ofType:nil) {
			img0022Layer9 = UIImage(contentsOfFile:imagePath)
		}else {
			print("** Warning: Could not create image from '_0022_Layer-9.png'. Please make sure that it is added to the project directly (not in a folder reference).")
		}
		_0022Layer9.image = img0022Layer9
		_0022Layer9.contentMode = .Center
		_0022Layer9.layer.position = CGPoint(x:375.000, y:142.500)
		__scaling__.addSubview(_0022Layer9)
		viewsByName["_0022_Layer-9"] = _0022Layer9

		let _0023Layer8 = UIImageView()
		_0023Layer8.bounds = CGRect(x:0, y:0, width:750.0, height:285.0)
		var img0023Layer8: UIImage!
		if let imagePath = bundle.pathForResource("_0023_Layer-8.png", ofType:nil) {
			img0023Layer8 = UIImage(contentsOfFile:imagePath)
		}else {
			print("** Warning: Could not create image from '_0023_Layer-8.png'. Please make sure that it is added to the project directly (not in a folder reference).")
		}
		_0023Layer8.image = img0023Layer8
		_0023Layer8.contentMode = .Center
		_0023Layer8.layer.position = CGPoint(x:375.000, y:142.500)
		__scaling__.addSubview(_0023Layer8)
		viewsByName["_0023_Layer-8"] = _0023Layer8

		let _0024Layer7 = UIImageView()
		_0024Layer7.bounds = CGRect(x:0, y:0, width:750.0, height:285.0)
		var img0024Layer7: UIImage!
		if let imagePath = bundle.pathForResource("_0024_Layer-7.png", ofType:nil) {
			img0024Layer7 = UIImage(contentsOfFile:imagePath)
		}else {
			print("** Warning: Could not create image from '_0024_Layer-7.png'. Please make sure that it is added to the project directly (not in a folder reference).")
		}
		_0024Layer7.image = img0024Layer7
		_0024Layer7.contentMode = .Center
		_0024Layer7.layer.position = CGPoint(x:375.000, y:142.500)
		__scaling__.addSubview(_0024Layer7)
		viewsByName["_0024_Layer-7"] = _0024Layer7

		let _0025Layer6 = UIImageView()
		_0025Layer6.bounds = CGRect(x:0, y:0, width:750.0, height:285.0)
		var img0025Layer6: UIImage!
		if let imagePath = bundle.pathForResource("_0025_Layer-6.png", ofType:nil) {
			img0025Layer6 = UIImage(contentsOfFile:imagePath)
		}else {
			print("** Warning: Could not create image from '_0025_Layer-6.png'. Please make sure that it is added to the project directly (not in a folder reference).")
		}
		_0025Layer6.image = img0025Layer6
		_0025Layer6.contentMode = .Center
		_0025Layer6.layer.position = CGPoint(x:375.000, y:142.500)
		__scaling__.addSubview(_0025Layer6)
		viewsByName["_0025_Layer-6"] = _0025Layer6

		let _0026Layer5 = UIImageView()
		_0026Layer5.bounds = CGRect(x:0, y:0, width:750.0, height:285.0)
		var img0026Layer5: UIImage!
		if let imagePath = bundle.pathForResource("_0026_Layer-5.png", ofType:nil) {
			img0026Layer5 = UIImage(contentsOfFile:imagePath)
		}else {
			print("** Warning: Could not create image from '_0026_Layer-5.png'. Please make sure that it is added to the project directly (not in a folder reference).")
		}
		_0026Layer5.image = img0026Layer5
		_0026Layer5.contentMode = .Center
		_0026Layer5.layer.position = CGPoint(x:375.000, y:142.500)
		__scaling__.addSubview(_0026Layer5)
		viewsByName["_0026_Layer-5"] = _0026Layer5

		let _0027Layer4 = UIImageView()
		_0027Layer4.bounds = CGRect(x:0, y:0, width:750.0, height:285.0)
		var img0027Layer4: UIImage!
		if let imagePath = bundle.pathForResource("_0027_Layer-4.png", ofType:nil) {
			img0027Layer4 = UIImage(contentsOfFile:imagePath)
		}else {
			print("** Warning: Could not create image from '_0027_Layer-4.png'. Please make sure that it is added to the project directly (not in a folder reference).")
		}
		_0027Layer4.image = img0027Layer4
		_0027Layer4.contentMode = .Center
		_0027Layer4.layer.position = CGPoint(x:375.000, y:142.500)
		__scaling__.addSubview(_0027Layer4)
		viewsByName["_0027_Layer-4"] = _0027Layer4

		let _0028Layer3 = UIImageView()
		_0028Layer3.bounds = CGRect(x:0, y:0, width:750.0, height:285.0)
		var img0028Layer3: UIImage!
		if let imagePath = bundle.pathForResource("_0028_Layer-3.png", ofType:nil) {
			img0028Layer3 = UIImage(contentsOfFile:imagePath)
		}else {
			print("** Warning: Could not create image from '_0028_Layer-3.png'. Please make sure that it is added to the project directly (not in a folder reference).")
		}
		_0028Layer3.image = img0028Layer3
		_0028Layer3.contentMode = .Center
		_0028Layer3.layer.position = CGPoint(x:375.000, y:142.500)
		__scaling__.addSubview(_0028Layer3)
		viewsByName["_0028_Layer-3"] = _0028Layer3

		let _0029Layer2 = UIImageView()
		_0029Layer2.bounds = CGRect(x:0, y:0, width:750.0, height:285.0)
		var img0029Layer2: UIImage!
		if let imagePath = bundle.pathForResource("_0029_Layer-2.png", ofType:nil) {
			img0029Layer2 = UIImage(contentsOfFile:imagePath)
		}else {
			print("** Warning: Could not create image from '_0029_Layer-2.png'. Please make sure that it is added to the project directly (not in a folder reference).")
		}
		_0029Layer2.image = img0029Layer2
		_0029Layer2.contentMode = .Center
		_0029Layer2.layer.position = CGPoint(x:375.000, y:142.500)
		__scaling__.addSubview(_0029Layer2)
		viewsByName["_0029_Layer-2"] = _0029Layer2

		let _0030Layer1 = UIImageView()
		_0030Layer1.bounds = CGRect(x:0, y:0, width:750.0, height:285.0)
		var img0030Layer1: UIImage!
		if let imagePath = bundle.pathForResource("_0030_Layer-1.png", ofType:nil) {
			img0030Layer1 = UIImage(contentsOfFile:imagePath)
		}else {
			print("** Warning: Could not create image from '_0030_Layer-1.png'. Please make sure that it is added to the project directly (not in a folder reference).")
		}
		_0030Layer1.image = img0030Layer1
		_0030Layer1.contentMode = .Center
		_0030Layer1.layer.position = CGPoint(x:375.000, y:142.500)
		__scaling__.addSubview(_0030Layer1)
		viewsByName["_0030_Layer-1"] = _0030Layer1

		self.viewsByName = viewsByName
	}

	// - MARK: carousel_4_animation

	func addCarousel4Animation() {
		addCarousel4AnimationWithBeginTime(0, fillMode: kCAFillModeBoth, removedOnCompletion: false, completion: nil)
	}

	func addCarousel4Animation(completion: ((Bool) -> Void)?) {
		addCarousel4AnimationWithBeginTime(0, fillMode: kCAFillModeBoth, removedOnCompletion: false, completion: completion)
	}

	func addCarousel4Animation(removedOnCompletion removedOnCompletion: Bool) {
		addCarousel4AnimationWithBeginTime(0, fillMode: removedOnCompletion ? kCAFillModeRemoved : kCAFillModeBoth, removedOnCompletion: removedOnCompletion, completion: nil)
	}

	func addCarousel4Animation(removedOnCompletion removedOnCompletion: Bool, completion: ((Bool) -> Void)?) {
		addCarousel4AnimationWithBeginTime(0, fillMode: removedOnCompletion ? kCAFillModeRemoved : kCAFillModeBoth, removedOnCompletion: removedOnCompletion, completion: completion)
	}

	func addCarousel4AnimationWithBeginTime(beginTime: CFTimeInterval, fillMode: String, removedOnCompletion: Bool, completion: ((Bool) -> Void)?) {
		let linearTiming = CAMediaTimingFunction(name: kCAMediaTimingFunctionLinear)
		if let complete = completion {
			let representativeAnimation = CABasicAnimation(keyPath: "not.a.real.key")
			representativeAnimation.duration = 1.210
			representativeAnimation.delegate = self
			self.layer.addAnimation(representativeAnimation, forKey: "Carousel4Animation")
			self.animationCompletions[layer.animationForKey("Carousel4Animation")!] = complete
		}

		let _0022Layer9OpacityAnimation = CAKeyframeAnimation(keyPath: "opacity")
		_0022Layer9OpacityAnimation.duration = 1.210
		_0022Layer9OpacityAnimation.values = [0.000 as Float, 0.000 as Float, 1.000 as Float, 1.000 as Float]
		_0022Layer9OpacityAnimation.keyTimes = [0.000 as Float, 0.256 as Float, 0.264 as Float, 1.000 as Float]
		_0022Layer9OpacityAnimation.timingFunctions = [linearTiming, linearTiming, linearTiming]
		_0022Layer9OpacityAnimation.beginTime = beginTime
		_0022Layer9OpacityAnimation.fillMode = fillMode
		_0022Layer9OpacityAnimation.removedOnCompletion = removedOnCompletion
		self.viewsByName["_0022_Layer-9"]?.layer.addAnimation(_0022Layer9OpacityAnimation, forKey:"carousel_4_animation_Opacity")

		let _0007Layer24OpacityAnimation = CAKeyframeAnimation(keyPath: "opacity")
		_0007Layer24OpacityAnimation.duration = 1.210
		_0007Layer24OpacityAnimation.values = [0.000 as Float, 0.000 as Float, 1.000 as Float, 1.000 as Float]
		_0007Layer24OpacityAnimation.keyTimes = [0.000 as Float, 0.760 as Float, 0.769 as Float, 1.000 as Float]
		_0007Layer24OpacityAnimation.timingFunctions = [linearTiming, linearTiming, linearTiming]
		_0007Layer24OpacityAnimation.beginTime = beginTime
		_0007Layer24OpacityAnimation.fillMode = fillMode
		_0007Layer24OpacityAnimation.removedOnCompletion = removedOnCompletion
		self.viewsByName["_0007_Layer-24"]?.layer.addAnimation(_0007Layer24OpacityAnimation, forKey:"carousel_4_animation_Opacity")

		let _0024Layer7OpacityAnimation = CAKeyframeAnimation(keyPath: "opacity")
		_0024Layer7OpacityAnimation.duration = 1.210
		_0024Layer7OpacityAnimation.values = [0.000 as Float, 0.000 as Float, 1.000 as Float, 1.000 as Float]
		_0024Layer7OpacityAnimation.keyTimes = [0.000 as Float, 0.190 as Float, 0.198 as Float, 1.000 as Float]
		_0024Layer7OpacityAnimation.timingFunctions = [linearTiming, linearTiming, linearTiming]
		_0024Layer7OpacityAnimation.beginTime = beginTime
		_0024Layer7OpacityAnimation.fillMode = fillMode
		_0024Layer7OpacityAnimation.removedOnCompletion = removedOnCompletion
		self.viewsByName["_0024_Layer-7"]?.layer.addAnimation(_0024Layer7OpacityAnimation, forKey:"carousel_4_animation_Opacity")

		let _0016Layer15OpacityAnimation = CAKeyframeAnimation(keyPath: "opacity")
		_0016Layer15OpacityAnimation.duration = 1.210
		_0016Layer15OpacityAnimation.values = [0.000 as Float, 0.000 as Float, 1.000 as Float, 1.000 as Float]
		_0016Layer15OpacityAnimation.keyTimes = [0.000 as Float, 0.463 as Float, 0.471 as Float, 1.000 as Float]
		_0016Layer15OpacityAnimation.timingFunctions = [linearTiming, linearTiming, linearTiming]
		_0016Layer15OpacityAnimation.beginTime = beginTime
		_0016Layer15OpacityAnimation.fillMode = fillMode
		_0016Layer15OpacityAnimation.removedOnCompletion = removedOnCompletion
		self.viewsByName["_0016_Layer-15"]?.layer.addAnimation(_0016Layer15OpacityAnimation, forKey:"carousel_4_animation_Opacity")

		let _0026Layer5OpacityAnimation = CAKeyframeAnimation(keyPath: "opacity")
		_0026Layer5OpacityAnimation.duration = 1.210
		_0026Layer5OpacityAnimation.values = [0.000 as Float, 0.000 as Float, 1.000 as Float, 1.000 as Float]
		_0026Layer5OpacityAnimation.keyTimes = [0.000 as Float, 0.124 as Float, 0.132 as Float, 1.000 as Float]
		_0026Layer5OpacityAnimation.timingFunctions = [linearTiming, linearTiming, linearTiming]
		_0026Layer5OpacityAnimation.beginTime = beginTime
		_0026Layer5OpacityAnimation.fillMode = fillMode
		_0026Layer5OpacityAnimation.removedOnCompletion = removedOnCompletion
		self.viewsByName["_0026_Layer-5"]?.layer.addAnimation(_0026Layer5OpacityAnimation, forKey:"carousel_4_animation_Opacity")

		let _0015Layer16OpacityAnimation = CAKeyframeAnimation(keyPath: "opacity")
		_0015Layer16OpacityAnimation.duration = 1.210
		_0015Layer16OpacityAnimation.values = [0.000 as Float, 0.000 as Float, 1.000 as Float, 1.000 as Float]
		_0015Layer16OpacityAnimation.keyTimes = [0.000 as Float, 0.496 as Float, 0.504 as Float, 1.000 as Float]
		_0015Layer16OpacityAnimation.timingFunctions = [linearTiming, linearTiming, linearTiming]
		_0015Layer16OpacityAnimation.beginTime = beginTime
		_0015Layer16OpacityAnimation.fillMode = fillMode
		_0015Layer16OpacityAnimation.removedOnCompletion = removedOnCompletion
		self.viewsByName["_0015_Layer-16"]?.layer.addAnimation(_0015Layer16OpacityAnimation, forKey:"carousel_4_animation_Opacity")

		let _0020Layer11OpacityAnimation = CAKeyframeAnimation(keyPath: "opacity")
		_0020Layer11OpacityAnimation.duration = 1.210
		_0020Layer11OpacityAnimation.values = [0.000 as Float, 0.000 as Float, 1.000 as Float, 1.000 as Float]
		_0020Layer11OpacityAnimation.keyTimes = [0.000 as Float, 0.322 as Float, 0.331 as Float, 1.000 as Float]
		_0020Layer11OpacityAnimation.timingFunctions = [linearTiming, linearTiming, linearTiming]
		_0020Layer11OpacityAnimation.beginTime = beginTime
		_0020Layer11OpacityAnimation.fillMode = fillMode
		_0020Layer11OpacityAnimation.removedOnCompletion = removedOnCompletion
		self.viewsByName["_0020_Layer-11"]?.layer.addAnimation(_0020Layer11OpacityAnimation, forKey:"carousel_4_animation_Opacity")

		let _0002Layer29OpacityAnimation = CAKeyframeAnimation(keyPath: "opacity")
		_0002Layer29OpacityAnimation.duration = 1.210
		_0002Layer29OpacityAnimation.values = [0.000 as Float, 0.000 as Float, 1.000 as Float, 1.000 as Float]
		_0002Layer29OpacityAnimation.keyTimes = [0.000 as Float, 0.926 as Float, 0.934 as Float, 1.000 as Float]
		_0002Layer29OpacityAnimation.timingFunctions = [linearTiming, linearTiming, linearTiming]
		_0002Layer29OpacityAnimation.beginTime = beginTime
		_0002Layer29OpacityAnimation.fillMode = fillMode
		_0002Layer29OpacityAnimation.removedOnCompletion = removedOnCompletion
		self.viewsByName["_0002_Layer-29"]?.layer.addAnimation(_0002Layer29OpacityAnimation, forKey:"carousel_4_animation_Opacity")

		let _0021Layer10OpacityAnimation = CAKeyframeAnimation(keyPath: "opacity")
		_0021Layer10OpacityAnimation.duration = 1.210
		_0021Layer10OpacityAnimation.values = [0.000 as Float, 0.000 as Float, 1.000 as Float, 1.000 as Float]
		_0021Layer10OpacityAnimation.keyTimes = [0.000 as Float, 0.289 as Float, 0.298 as Float, 1.000 as Float]
		_0021Layer10OpacityAnimation.timingFunctions = [linearTiming, linearTiming, linearTiming]
		_0021Layer10OpacityAnimation.beginTime = beginTime
		_0021Layer10OpacityAnimation.fillMode = fillMode
		_0021Layer10OpacityAnimation.removedOnCompletion = removedOnCompletion
		self.viewsByName["_0021_Layer-10"]?.layer.addAnimation(_0021Layer10OpacityAnimation, forKey:"carousel_4_animation_Opacity")

		let _0017Layer14OpacityAnimation = CAKeyframeAnimation(keyPath: "opacity")
		_0017Layer14OpacityAnimation.duration = 1.210
		_0017Layer14OpacityAnimation.values = [0.000 as Float, 0.000 as Float, 1.000 as Float, 1.000 as Float]
		_0017Layer14OpacityAnimation.keyTimes = [0.000 as Float, 0.430 as Float, 0.438 as Float, 1.000 as Float]
		_0017Layer14OpacityAnimation.timingFunctions = [linearTiming, linearTiming, linearTiming]
		_0017Layer14OpacityAnimation.beginTime = beginTime
		_0017Layer14OpacityAnimation.fillMode = fillMode
		_0017Layer14OpacityAnimation.removedOnCompletion = removedOnCompletion
		self.viewsByName["_0017_Layer-14"]?.layer.addAnimation(_0017Layer14OpacityAnimation, forKey:"carousel_4_animation_Opacity")

		let _0018Layer13OpacityAnimation = CAKeyframeAnimation(keyPath: "opacity")
		_0018Layer13OpacityAnimation.duration = 1.210
		_0018Layer13OpacityAnimation.values = [0.000 as Float, 0.000 as Float, 1.000 as Float, 1.000 as Float]
		_0018Layer13OpacityAnimation.keyTimes = [0.000 as Float, 0.397 as Float, 0.405 as Float, 1.000 as Float]
		_0018Layer13OpacityAnimation.timingFunctions = [linearTiming, linearTiming, linearTiming]
		_0018Layer13OpacityAnimation.beginTime = beginTime
		_0018Layer13OpacityAnimation.fillMode = fillMode
		_0018Layer13OpacityAnimation.removedOnCompletion = removedOnCompletion
		self.viewsByName["_0018_Layer-13"]?.layer.addAnimation(_0018Layer13OpacityAnimation, forKey:"carousel_4_animation_Opacity")

		let _0010Layer21OpacityAnimation = CAKeyframeAnimation(keyPath: "opacity")
		_0010Layer21OpacityAnimation.duration = 1.210
		_0010Layer21OpacityAnimation.values = [0.000 as Float, 0.000 as Float, 1.000 as Float, 1.000 as Float]
		_0010Layer21OpacityAnimation.keyTimes = [0.000 as Float, 0.661 as Float, 0.669 as Float, 1.000 as Float]
		_0010Layer21OpacityAnimation.timingFunctions = [linearTiming, linearTiming, linearTiming]
		_0010Layer21OpacityAnimation.beginTime = beginTime
		_0010Layer21OpacityAnimation.fillMode = fillMode
		_0010Layer21OpacityAnimation.removedOnCompletion = removedOnCompletion
		self.viewsByName["_0010_Layer-21"]?.layer.addAnimation(_0010Layer21OpacityAnimation, forKey:"carousel_4_animation_Opacity")

		let _0005Layer26OpacityAnimation = CAKeyframeAnimation(keyPath: "opacity")
		_0005Layer26OpacityAnimation.duration = 1.210
		_0005Layer26OpacityAnimation.values = [0.000 as Float, 0.000 as Float, 1.000 as Float, 1.000 as Float]
		_0005Layer26OpacityAnimation.keyTimes = [0.000 as Float, 0.826 as Float, 0.835 as Float, 1.000 as Float]
		_0005Layer26OpacityAnimation.timingFunctions = [linearTiming, linearTiming, linearTiming]
		_0005Layer26OpacityAnimation.beginTime = beginTime
		_0005Layer26OpacityAnimation.fillMode = fillMode
		_0005Layer26OpacityAnimation.removedOnCompletion = removedOnCompletion
		self.viewsByName["_0005_Layer-26"]?.layer.addAnimation(_0005Layer26OpacityAnimation, forKey:"carousel_4_animation_Opacity")

		let _0029Layer2OpacityAnimation = CAKeyframeAnimation(keyPath: "opacity")
		_0029Layer2OpacityAnimation.duration = 1.210
		_0029Layer2OpacityAnimation.values = [0.000 as Float, 0.000 as Float, 1.000 as Float, 1.000 as Float]
		_0029Layer2OpacityAnimation.keyTimes = [0.000 as Float, 0.025 as Float, 0.033 as Float, 1.000 as Float]
		_0029Layer2OpacityAnimation.timingFunctions = [linearTiming, linearTiming, linearTiming]
		_0029Layer2OpacityAnimation.beginTime = beginTime
		_0029Layer2OpacityAnimation.fillMode = fillMode
		_0029Layer2OpacityAnimation.removedOnCompletion = removedOnCompletion
		self.viewsByName["_0029_Layer-2"]?.layer.addAnimation(_0029Layer2OpacityAnimation, forKey:"carousel_4_animation_Opacity")

		let _0004Layer27OpacityAnimation = CAKeyframeAnimation(keyPath: "opacity")
		_0004Layer27OpacityAnimation.duration = 1.210
		_0004Layer27OpacityAnimation.values = [0.000 as Float, 0.000 as Float, 1.000 as Float, 1.000 as Float]
		_0004Layer27OpacityAnimation.keyTimes = [0.000 as Float, 0.860 as Float, 0.868 as Float, 1.000 as Float]
		_0004Layer27OpacityAnimation.timingFunctions = [linearTiming, linearTiming, linearTiming]
		_0004Layer27OpacityAnimation.beginTime = beginTime
		_0004Layer27OpacityAnimation.fillMode = fillMode
		_0004Layer27OpacityAnimation.removedOnCompletion = removedOnCompletion
		self.viewsByName["_0004_Layer-27"]?.layer.addAnimation(_0004Layer27OpacityAnimation, forKey:"carousel_4_animation_Opacity")

		let _0025Layer6OpacityAnimation = CAKeyframeAnimation(keyPath: "opacity")
		_0025Layer6OpacityAnimation.duration = 1.210
		_0025Layer6OpacityAnimation.values = [0.000 as Float, 0.000 as Float, 1.000 as Float, 1.000 as Float]
		_0025Layer6OpacityAnimation.keyTimes = [0.000 as Float, 0.157 as Float, 0.165 as Float, 1.000 as Float]
		_0025Layer6OpacityAnimation.timingFunctions = [linearTiming, linearTiming, linearTiming]
		_0025Layer6OpacityAnimation.beginTime = beginTime
		_0025Layer6OpacityAnimation.fillMode = fillMode
		_0025Layer6OpacityAnimation.removedOnCompletion = removedOnCompletion
		self.viewsByName["_0025_Layer-6"]?.layer.addAnimation(_0025Layer6OpacityAnimation, forKey:"carousel_4_animation_Opacity")

		let _0013Layer18OpacityAnimation = CAKeyframeAnimation(keyPath: "opacity")
		_0013Layer18OpacityAnimation.duration = 1.210
		_0013Layer18OpacityAnimation.values = [0.000 as Float, 0.000 as Float, 1.000 as Float, 1.000 as Float]
		_0013Layer18OpacityAnimation.keyTimes = [0.000 as Float, 0.562 as Float, 0.570 as Float, 1.000 as Float]
		_0013Layer18OpacityAnimation.timingFunctions = [linearTiming, linearTiming, linearTiming]
		_0013Layer18OpacityAnimation.beginTime = beginTime
		_0013Layer18OpacityAnimation.fillMode = fillMode
		_0013Layer18OpacityAnimation.removedOnCompletion = removedOnCompletion
		self.viewsByName["_0013_Layer-18"]?.layer.addAnimation(_0013Layer18OpacityAnimation, forKey:"carousel_4_animation_Opacity")

		let _0003Layer28OpacityAnimation = CAKeyframeAnimation(keyPath: "opacity")
		_0003Layer28OpacityAnimation.duration = 1.210
		_0003Layer28OpacityAnimation.values = [0.000 as Float, 0.000 as Float, 1.000 as Float, 1.000 as Float]
		_0003Layer28OpacityAnimation.keyTimes = [0.000 as Float, 0.893 as Float, 0.901 as Float, 1.000 as Float]
		_0003Layer28OpacityAnimation.timingFunctions = [linearTiming, linearTiming, linearTiming]
		_0003Layer28OpacityAnimation.beginTime = beginTime
		_0003Layer28OpacityAnimation.fillMode = fillMode
		_0003Layer28OpacityAnimation.removedOnCompletion = removedOnCompletion
		self.viewsByName["_0003_Layer-28"]?.layer.addAnimation(_0003Layer28OpacityAnimation, forKey:"carousel_4_animation_Opacity")

		let _0014Layer17OpacityAnimation = CAKeyframeAnimation(keyPath: "opacity")
		_0014Layer17OpacityAnimation.duration = 1.210
		_0014Layer17OpacityAnimation.values = [0.000 as Float, 0.000 as Float, 1.000 as Float, 1.000 as Float]
		_0014Layer17OpacityAnimation.keyTimes = [0.000 as Float, 0.529 as Float, 0.537 as Float, 1.000 as Float]
		_0014Layer17OpacityAnimation.timingFunctions = [linearTiming, linearTiming, linearTiming]
		_0014Layer17OpacityAnimation.beginTime = beginTime
		_0014Layer17OpacityAnimation.fillMode = fillMode
		_0014Layer17OpacityAnimation.removedOnCompletion = removedOnCompletion
		self.viewsByName["_0014_Layer-17"]?.layer.addAnimation(_0014Layer17OpacityAnimation, forKey:"carousel_4_animation_Opacity")

		let _0027Layer4OpacityAnimation = CAKeyframeAnimation(keyPath: "opacity")
		_0027Layer4OpacityAnimation.duration = 1.210
		_0027Layer4OpacityAnimation.values = [0.000 as Float, 0.000 as Float, 1.000 as Float, 1.000 as Float]
		_0027Layer4OpacityAnimation.keyTimes = [0.000 as Float, 0.091 as Float, 0.099 as Float, 1.000 as Float]
		_0027Layer4OpacityAnimation.timingFunctions = [linearTiming, linearTiming, linearTiming]
		_0027Layer4OpacityAnimation.beginTime = beginTime
		_0027Layer4OpacityAnimation.fillMode = fillMode
		_0027Layer4OpacityAnimation.removedOnCompletion = removedOnCompletion
		self.viewsByName["_0027_Layer-4"]?.layer.addAnimation(_0027Layer4OpacityAnimation, forKey:"carousel_4_animation_Opacity")

		let _0001Layer30OpacityAnimation = CAKeyframeAnimation(keyPath: "opacity")
		_0001Layer30OpacityAnimation.duration = 1.210
		_0001Layer30OpacityAnimation.values = [0.000 as Float, 0.000 as Float, 1.000 as Float, 1.000 as Float]
		_0001Layer30OpacityAnimation.keyTimes = [0.000 as Float, 0.959 as Float, 0.967 as Float, 1.000 as Float]
		_0001Layer30OpacityAnimation.timingFunctions = [linearTiming, linearTiming, linearTiming]
		_0001Layer30OpacityAnimation.beginTime = beginTime
		_0001Layer30OpacityAnimation.fillMode = fillMode
		_0001Layer30OpacityAnimation.removedOnCompletion = removedOnCompletion
		self.viewsByName["_0001_Layer-30"]?.layer.addAnimation(_0001Layer30OpacityAnimation, forKey:"carousel_4_animation_Opacity")

		let _0011Layer20OpacityAnimation = CAKeyframeAnimation(keyPath: "opacity")
		_0011Layer20OpacityAnimation.duration = 1.210
		_0011Layer20OpacityAnimation.values = [0.000 as Float, 0.000 as Float, 1.000 as Float, 1.000 as Float]
		_0011Layer20OpacityAnimation.keyTimes = [0.000 as Float, 0.628 as Float, 0.636 as Float, 1.000 as Float]
		_0011Layer20OpacityAnimation.timingFunctions = [linearTiming, linearTiming, linearTiming]
		_0011Layer20OpacityAnimation.beginTime = beginTime
		_0011Layer20OpacityAnimation.fillMode = fillMode
		_0011Layer20OpacityAnimation.removedOnCompletion = removedOnCompletion
		self.viewsByName["_0011_Layer-20"]?.layer.addAnimation(_0011Layer20OpacityAnimation, forKey:"carousel_4_animation_Opacity")

		let _0028Layer3OpacityAnimation = CAKeyframeAnimation(keyPath: "opacity")
		_0028Layer3OpacityAnimation.duration = 1.210
		_0028Layer3OpacityAnimation.values = [0.000 as Float, 0.000 as Float, 1.000 as Float, 1.000 as Float]
		_0028Layer3OpacityAnimation.keyTimes = [0.000 as Float, 0.058 as Float, 0.066 as Float, 1.000 as Float]
		_0028Layer3OpacityAnimation.timingFunctions = [linearTiming, linearTiming, linearTiming]
		_0028Layer3OpacityAnimation.beginTime = beginTime
		_0028Layer3OpacityAnimation.fillMode = fillMode
		_0028Layer3OpacityAnimation.removedOnCompletion = removedOnCompletion
		self.viewsByName["_0028_Layer-3"]?.layer.addAnimation(_0028Layer3OpacityAnimation, forKey:"carousel_4_animation_Opacity")

		let _0006Layer25OpacityAnimation = CAKeyframeAnimation(keyPath: "opacity")
		_0006Layer25OpacityAnimation.duration = 1.210
		_0006Layer25OpacityAnimation.values = [0.000 as Float, 0.000 as Float, 1.000 as Float, 1.000 as Float]
		_0006Layer25OpacityAnimation.keyTimes = [0.000 as Float, 0.793 as Float, 0.802 as Float, 1.000 as Float]
		_0006Layer25OpacityAnimation.timingFunctions = [linearTiming, linearTiming, linearTiming]
		_0006Layer25OpacityAnimation.beginTime = beginTime
		_0006Layer25OpacityAnimation.fillMode = fillMode
		_0006Layer25OpacityAnimation.removedOnCompletion = removedOnCompletion
		self.viewsByName["_0006_Layer-25"]?.layer.addAnimation(_0006Layer25OpacityAnimation, forKey:"carousel_4_animation_Opacity")

		let _0008Layer23OpacityAnimation = CAKeyframeAnimation(keyPath: "opacity")
		_0008Layer23OpacityAnimation.duration = 1.210
		_0008Layer23OpacityAnimation.values = [0.000 as Float, 0.000 as Float, 1.000 as Float, 1.000 as Float]
		_0008Layer23OpacityAnimation.keyTimes = [0.000 as Float, 0.727 as Float, 0.736 as Float, 1.000 as Float]
		_0008Layer23OpacityAnimation.timingFunctions = [linearTiming, linearTiming, linearTiming]
		_0008Layer23OpacityAnimation.beginTime = beginTime
		_0008Layer23OpacityAnimation.fillMode = fillMode
		_0008Layer23OpacityAnimation.removedOnCompletion = removedOnCompletion
		self.viewsByName["_0008_Layer-23"]?.layer.addAnimation(_0008Layer23OpacityAnimation, forKey:"carousel_4_animation_Opacity")

		let _0023Layer8OpacityAnimation = CAKeyframeAnimation(keyPath: "opacity")
		_0023Layer8OpacityAnimation.duration = 1.210
		_0023Layer8OpacityAnimation.values = [0.000 as Float, 0.000 as Float, 1.000 as Float, 1.000 as Float]
		_0023Layer8OpacityAnimation.keyTimes = [0.000 as Float, 0.223 as Float, 0.231 as Float, 1.000 as Float]
		_0023Layer8OpacityAnimation.timingFunctions = [linearTiming, linearTiming, linearTiming]
		_0023Layer8OpacityAnimation.beginTime = beginTime
		_0023Layer8OpacityAnimation.fillMode = fillMode
		_0023Layer8OpacityAnimation.removedOnCompletion = removedOnCompletion
		self.viewsByName["_0023_Layer-8"]?.layer.addAnimation(_0023Layer8OpacityAnimation, forKey:"carousel_4_animation_Opacity")

		let _0000Layer31OpacityAnimation = CAKeyframeAnimation(keyPath: "opacity")
		_0000Layer31OpacityAnimation.duration = 1.210
		_0000Layer31OpacityAnimation.values = [0.000 as Float, 0.000 as Float, 1.000 as Float]
		_0000Layer31OpacityAnimation.keyTimes = [0.000 as Float, 0.992 as Float, 1.000 as Float]
		_0000Layer31OpacityAnimation.timingFunctions = [linearTiming, linearTiming]
		_0000Layer31OpacityAnimation.beginTime = beginTime
		_0000Layer31OpacityAnimation.fillMode = fillMode
		_0000Layer31OpacityAnimation.removedOnCompletion = removedOnCompletion
		self.viewsByName["_0000_Layer-31"]?.layer.addAnimation(_0000Layer31OpacityAnimation, forKey:"carousel_4_animation_Opacity")

		let _0012Layer19OpacityAnimation = CAKeyframeAnimation(keyPath: "opacity")
		_0012Layer19OpacityAnimation.duration = 1.210
		_0012Layer19OpacityAnimation.values = [0.000 as Float, 0.000 as Float, 1.000 as Float, 1.000 as Float]
		_0012Layer19OpacityAnimation.keyTimes = [0.000 as Float, 0.595 as Float, 0.603 as Float, 1.000 as Float]
		_0012Layer19OpacityAnimation.timingFunctions = [linearTiming, linearTiming, linearTiming]
		_0012Layer19OpacityAnimation.beginTime = beginTime
		_0012Layer19OpacityAnimation.fillMode = fillMode
		_0012Layer19OpacityAnimation.removedOnCompletion = removedOnCompletion
		self.viewsByName["_0012_Layer-19"]?.layer.addAnimation(_0012Layer19OpacityAnimation, forKey:"carousel_4_animation_Opacity")

		let _0009Layer22OpacityAnimation = CAKeyframeAnimation(keyPath: "opacity")
		_0009Layer22OpacityAnimation.duration = 1.210
		_0009Layer22OpacityAnimation.values = [0.000 as Float, 0.000 as Float, 1.000 as Float, 1.000 as Float]
		_0009Layer22OpacityAnimation.keyTimes = [0.000 as Float, 0.694 as Float, 0.702 as Float, 1.000 as Float]
		_0009Layer22OpacityAnimation.timingFunctions = [linearTiming, linearTiming, linearTiming]
		_0009Layer22OpacityAnimation.beginTime = beginTime
		_0009Layer22OpacityAnimation.fillMode = fillMode
		_0009Layer22OpacityAnimation.removedOnCompletion = removedOnCompletion
		self.viewsByName["_0009_Layer-22"]?.layer.addAnimation(_0009Layer22OpacityAnimation, forKey:"carousel_4_animation_Opacity")

		let _0019Layer12OpacityAnimation = CAKeyframeAnimation(keyPath: "opacity")
		_0019Layer12OpacityAnimation.duration = 1.210
		_0019Layer12OpacityAnimation.values = [0.000 as Float, 0.000 as Float, 1.000 as Float, 1.000 as Float]
		_0019Layer12OpacityAnimation.keyTimes = [0.000 as Float, 0.364 as Float, 0.372 as Float, 1.000 as Float]
		_0019Layer12OpacityAnimation.timingFunctions = [linearTiming, linearTiming, linearTiming]
		_0019Layer12OpacityAnimation.beginTime = beginTime
		_0019Layer12OpacityAnimation.fillMode = fillMode
		_0019Layer12OpacityAnimation.removedOnCompletion = removedOnCompletion
		self.viewsByName["_0019_Layer-12"]?.layer.addAnimation(_0019Layer12OpacityAnimation, forKey:"carousel_4_animation_Opacity")
	}

	func removeCarousel4Animation() {
		self.layer.removeAnimationForKey("Carousel4Animation")
		self.viewsByName["_0022_Layer-9"]?.layer.removeAnimationForKey("carousel_4_animation_Opacity")
		self.viewsByName["_0007_Layer-24"]?.layer.removeAnimationForKey("carousel_4_animation_Opacity")
		self.viewsByName["_0024_Layer-7"]?.layer.removeAnimationForKey("carousel_4_animation_Opacity")
		self.viewsByName["_0016_Layer-15"]?.layer.removeAnimationForKey("carousel_4_animation_Opacity")
		self.viewsByName["_0026_Layer-5"]?.layer.removeAnimationForKey("carousel_4_animation_Opacity")
		self.viewsByName["_0015_Layer-16"]?.layer.removeAnimationForKey("carousel_4_animation_Opacity")
		self.viewsByName["_0020_Layer-11"]?.layer.removeAnimationForKey("carousel_4_animation_Opacity")
		self.viewsByName["_0002_Layer-29"]?.layer.removeAnimationForKey("carousel_4_animation_Opacity")
		self.viewsByName["_0021_Layer-10"]?.layer.removeAnimationForKey("carousel_4_animation_Opacity")
		self.viewsByName["_0017_Layer-14"]?.layer.removeAnimationForKey("carousel_4_animation_Opacity")
		self.viewsByName["_0018_Layer-13"]?.layer.removeAnimationForKey("carousel_4_animation_Opacity")
		self.viewsByName["_0010_Layer-21"]?.layer.removeAnimationForKey("carousel_4_animation_Opacity")
		self.viewsByName["_0005_Layer-26"]?.layer.removeAnimationForKey("carousel_4_animation_Opacity")
		self.viewsByName["_0029_Layer-2"]?.layer.removeAnimationForKey("carousel_4_animation_Opacity")
		self.viewsByName["_0004_Layer-27"]?.layer.removeAnimationForKey("carousel_4_animation_Opacity")
		self.viewsByName["_0025_Layer-6"]?.layer.removeAnimationForKey("carousel_4_animation_Opacity")
		self.viewsByName["_0013_Layer-18"]?.layer.removeAnimationForKey("carousel_4_animation_Opacity")
		self.viewsByName["_0003_Layer-28"]?.layer.removeAnimationForKey("carousel_4_animation_Opacity")
		self.viewsByName["_0014_Layer-17"]?.layer.removeAnimationForKey("carousel_4_animation_Opacity")
		self.viewsByName["_0027_Layer-4"]?.layer.removeAnimationForKey("carousel_4_animation_Opacity")
		self.viewsByName["_0001_Layer-30"]?.layer.removeAnimationForKey("carousel_4_animation_Opacity")
		self.viewsByName["_0011_Layer-20"]?.layer.removeAnimationForKey("carousel_4_animation_Opacity")
		self.viewsByName["_0028_Layer-3"]?.layer.removeAnimationForKey("carousel_4_animation_Opacity")
		self.viewsByName["_0006_Layer-25"]?.layer.removeAnimationForKey("carousel_4_animation_Opacity")
		self.viewsByName["_0008_Layer-23"]?.layer.removeAnimationForKey("carousel_4_animation_Opacity")
		self.viewsByName["_0023_Layer-8"]?.layer.removeAnimationForKey("carousel_4_animation_Opacity")
		self.viewsByName["_0000_Layer-31"]?.layer.removeAnimationForKey("carousel_4_animation_Opacity")
		self.viewsByName["_0012_Layer-19"]?.layer.removeAnimationForKey("carousel_4_animation_Opacity")
		self.viewsByName["_0009_Layer-22"]?.layer.removeAnimationForKey("carousel_4_animation_Opacity")
		self.viewsByName["_0019_Layer-12"]?.layer.removeAnimationForKey("carousel_4_animation_Opacity")
	}

	override func animationDidStop(anim: CAAnimation, finished flag: Bool) {
		if let completion = self.animationCompletions[anim] {
			self.animationCompletions.removeValueForKey(anim)
			completion(flag)
		}
	}

	func removeAllAnimations() {
		for subview in viewsByName.values {
			subview.layer.removeAllAnimations()
		}
		self.layer.removeAnimationForKey("Carousel4Animation")
	}
}